default_config:
homeassistant:
  name: Whyte House
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  currency: AUD
  time_zone: Australia/Sydney
  auth_providers:
    - type: homeassistant
  packages: !include_dir_named integrations
  internal_url: !secret http_base_url_internal
  external_url: !secret http_base_url
  whitelist_external_dirs:
    - /config

group: !include_dir_merge_named groups/
automation: !include automations.yaml
