id: "3289473458972310"
alias: "bathroom: turn off lights on no occupancy detected when door is open"
description: >
  Turns off bathroom lights when the door is open and occupancy has not been 
  detected for a short period of time
mode: single
trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_motion_occupancy
    to: "off"
    from: "on"
    for: "00:02:00"
condition:
  - condition: state
    entity_id: input_boolean.away_mode
    state: "off"
  - condition: state
    entity_id: light.bathroom
    state: "on"
  - condition: state
    entity_id: binary_sensor.bathroom_door
    state: "on" # Door is open
action:
  - service: light.turn_off
    target:
      entity_id: light.bathroom
