id: '1610793781902'
alias: 'bathroom: turn off fan when shower occupancy not detected'
description: ''
trigger:
- platform: state
  entity_id: binary_sensor.bathroom_shower_occupancy
  to: 'off'
  from: 'on'
condition: []
action:
- service: notify.mobile_app_nicks_iphone
  data:
    title: Would have turned off bathroom fan
    message: >
      bathroom_shower_occupancy: {{ states(''binary_sensor.bathroom_shower_occupancy'') }}
      bathroom_climate_humidity_elevated: {{ states(''binary_sensor.bathroom_climate_humidity_elevated'') }}
      bathroom_climate_humidity_increasing: {{ states(''binary_sensor.bathroom_climate_humidity_increasing'') }}
      bathroom_climate_humidity: {{ states(''sensor.bathroom_climate_humidity'') }}
      bedroom_climate_humidity: {{ states(''sensor.bedroom_climate_humidity'') }}
# - service: fan.turn_off
#   data: {}
#   entity_id: fan.bathroom
mode: single
