id: "445E9F93-0F62-47BD-B2EC-097AA040FD11"
alias: "robot_vacuum: suggest to clean via notification when everyone leaves home"
description: ""
mode: single
trigger:
  - platform: state
    entity_id: group.all_people
    from: home
    to: not_home
condition:
  # Don't notify if proximity/zone based automation is triggered
  - condition: template
    value_template: >-
      {{ (now() - state_attr('automation.robot_vacuum_start_cleaning_whilst_away','last_triggered')).total_seconds() > 60 * 30 }}
  # Don't notify if already cleaned today
  - condition: template
    value_template: >-
      {{ strptime(states('input_datetime.osmo_last_clean'), '%Y-%m-%d %H:%M:%S') |
      as_local < now().replace(hour=0, minute=0, second=0) }}
  # Don't notify if already cleaning
  - condition: state
    entity_id: vacuum.osmo
    state: idle
  # Don't notify if away mode activated
  - condition: state
    entity_id: input_boolean.away_mode
    state: "off"
action:
  - service: notify.everyone
    data:
      title: Osmo
      message: No one is home. Begin cleaning?
      data:
        tag: osmo-no-one-home
        action_data:
          clear_tag: osmo-no-one-home
        actions:
          - action: "ROBOVAC_CLEAN_AUTO"
            title: Auto Clean
          - action: "ROBOVAC_CLEAN_QUICK"
            title: Quick Clean
          - action: "ROBOVAC_CLEAN_DEEP"
            title: Deep Clean
