id: '445E9F93-0F62-47BD-B2EC-097AA040FD11'
alias: 'robot_vacuum: suggest to clean via notification when everyone leaves home'
description: ''
mode: single
trigger:
  - platform: state
    entity_id: group.all_people
    from: home
    to: not_home
condition:
# Avoid notifying if already cleaned today
- condition: template
  value_template: >-
    {{ strptime(states('input_datetime.osmo_last_clean'), '%Y-%m-%d %H:%M:%S') |
    as_local < now().replace(hour=0, minute=0, second=0) }}
action:
- service: notify.everyone
  data:
    title: Osmo
    message: No one is home. Begin cleaning?
    data:
      tag: osmo-no-one-home
      action_data:
        clear_tag: osmo-no-one-home
      actions:
      - action: 'ROBOVAC_CLEAN_ALL'
        title: Clean All Areas
      - action: 'ROBOVAC_CLEAN_TILES'
        title: Clean Tiled Areas
