- id: '1532953292008'
  alias: Notify Garage Door 11pm
  trigger:
  - at: '23:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: cover.garage
    state: open
  action:
  - data:
      data:
        push:
          category: garage_door_open
      message: It is after 11pm and it appears the garage door is still open
      title: Garage Door Still Open
    service: notify.all_apps

- id: '1532954744042'
  alias: 'iOS: Close Garage Door'
  trigger:
  - event_data:
      actionName: GARAGE_DOOR_CLOSE
    event_type: ios.notification_action_fired
    platform: event
  condition: []
  action:
  - data:
      entity_id: cover.garage
    service: cover.close_cover
