default_config:
homeassistant:
  name: 313A
  latitude: -33.990236
  longitude: 151.090537
  elevation: 20
  unit_system: metric
  time_zone: Australia/Sydney
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.8.0/24
        - 192.168.24.0/24
  packages: !include_dir_named integrations
  internal_url: !secret http_base_url
  external_url: !secret http_base_url
  whitelist_external_dirs:
    - /config

group: !include_dir_merge_named groups/
automation: !include automations.yaml
