id: "1592101534049328"
alias: "laundry: broadcast on dryer completed"
description: ""
trigger:
  - entity_id: binary_sensor.dryer
    from: "on"
    platform: state
    to: "off"
condition:
  - condition: state
    entity_id: group.all_people
    state: home
  # Make sure we don't wake anyone up!
  - condition: time
    after: "09:00:00"
    before: "22:00:00"
action:
  - service: media_player.turn_on
    data: {}
    target:
      entity_id:
        - media_player.living_room_homepod
        - media_player.bedroom_homepod
  - service: media_player.volume_set
    entity_id:
      - media_player.living_room_homepod
      - media_player.bedroom_homepod
    data:
      volume_level: 0.5
  - service: tts.google_translate_say
    entity_id:
      - media_player.living_room_homepod
      - media_player.bedroom_homepod
    data:
      message: The dryer has finished!
