id: "1592101514693"
alias: "laundry: broadcast on washing machine completed"
description: ""
trigger:
  - entity_id: binary_sensor.washing_machine
    from: "on"
    platform: state
    to: "off"
condition:
  - condition: state
    entity_id: group.all_people
    state: home
  # Make sure we don't wake anyone up!
  - condition: state
    entity_id: binary_sensor.in_bed
    state: "off"
action:
  # Repeat the broadcast again if the laundry isn't visited.
  - repeat:
      sequence:
        - service: media_player.turn_on
          data: {}
          target:
            entity_id:
              - media_player.living_room_homepod
              - media_player.bedroom_homepod
        - service: media_player.volume_set
          entity_id:
            - media_player.living_room_homepod
            - media_player.bedroom_homepod
          data:
            volume_level: 0.5
        - service: tts.google_translate_say
          entity_id:
            - media_player.living_room_homepod
            - media_player.bedroom_homepod
          data:
            message: The washing machine has finished!

        - wait_for_trigger:
            - platform: state
              entity_id: binary_sensor.laundry_door
              to: "on"
          timeout: "00:25:00"
      until: <
        {{
        wait.trigger is not none
        or repeat.index > 3
        or is_state('group.all_people', 'not_home')
        or is_state('binary_sensor.in_bed', 'on')
        }}
