id: '1592101534049328'
alias: 'laundry: broadcast on dryer completed'
description: ''
trigger:
  - entity_id: binary_sensor.dryer
    from: 'on'
    platform: state
    to: 'off'
condition:
  - condition: state
    entity_id: group.all_people
    state: home
action:
  - service: media_player.turn_off
    data: {}
    target:
      entity_id:
        - media_player.owntone_output_samsung_8_series_55
        - media_player.owntone_output_soundbar_cast
  - service: media_player.turn_on
    data: {}
    target:
      entity_id:
        - media_player.owntone_output_living_room
        - media_player.owntone_output_bedroom
  - service: media_player.volume_set
    entity_id:
      - media_player.owntone_output_living_room
      - media_player.owntone_output_bedroom
    data:
      volume_level: 0.5
  - service: tts.google_translate_say
    entity_id:
      - media_player.owntone_server
    data:
      message: The dryer has finished!
