id: '1592102651795'
alias: 'laundry: broadcast on washing machine completed whilst away when arriving home'
description: ''
trigger:
  - entity_id: binary_sensor.washing_machine
    from: 'on'
    platform: state
    to: 'off'
condition:
  - condition: state
    entity_id: group.all_people
    state: not_home
action:
  - wait_template: '{{ is_state("group.all_people", "home") }}'
    timeout: '24:00:00'
  - delay: 00:05:00
  - service: media_player.volume_set
    entity_id:
      - media_player.kitchen_speaker
      - media_player.living_room_speaker
    data:
      volume_level: 0.5
  - service: tts.google_translate_say
    entity_id:
      - media_player.kitchen_speaker
      - media_player.living_room_speaker
    data:
      message: The washing machine finished whilst away
