id: "1592101534043894789"
alias: "laundry: cancel broadcasts"
description: ""
mode: single
trigger:
  - platform: state
    entity_id: group.all_people
    to: "not_home"
  - platform: state
    entity_id: binary_sensor.in_bed
    to: "on"
  - platform: state
    entity_id: binary_sensor.laundry_door
    to: "on"
  - platform: state
    entity_id: binary_sensor.front_door
    to: "on"
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: automation.laundry_broadcast_on_dryer_completed
            state: "on"
        sequence:
          - service: automation.turn_off
            target:
              entity_id: automation.laundry_broadcast_on_dryer_completed
          - service: automation.turn_on
            target:
              entity_id: automation.laundry_broadcast_on_dryer_completed
  - choose:
      - conditions:
          - condition: state
            entity_id: automation.when_washing_machine_completed_broadcast
            state: "on"
        sequence:
          - service: automation.turn_off
            target:
              entity_id: automation.when_washing_machine_completed_broadcast
          - service: automation.turn_on
            target:
              entity_id: automation.when_washing_machine_completed_broadcast
