id: '1609991469286'
alias: 'laundry: notify on laundry door open without recent home activity'
description: ''
trigger:
- type: opened
  platform: device
  device_id: 6ebac700fde711eabf1a89a94693ffa5
  entity_id: binary_sensor.laundry_door
  domain: binary_sensor
condition:
  # Alarm is disarmed
  - condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: disarmed
  # And no recent activity detected
  #   - Nick did not arrive home recently (10 mins)
  #   - Kate did not arrive home recently (10 mins)
  #   - Front door did not open or close recently (5 mins)
  - condition: template
    value_template: >-
      {{ not(
        (is_state('person.nick', 'home') and (now() - states.person.nick.last_changed).total_seconds() < 600) or
        (is_state('person.kate', 'home') and (now() - states.person.kate.last_changed).total_seconds() < 600) or
        (now() - states.binary_sensor.front_door.last_changed).total_seconds() < 300
      ) }}
action:
- service: notify.everyone
  data:
    title: Laundry Door Opened
    message: The laundry door was opened at {{ now().strftime('%I:%M %p') }} without recent activity
mode: single
