id: '1601038594262'
alias: 'laundry: notify (critical) on leak detected'
description: ''
trigger:
- type: moist
  platform: device
  device_id: a6104643fd6c11ea9adc5fd191831e65
  entity_id: binary_sensor.laundry_leak_water_leak
  domain: binary_sensor
condition: []
action:
- service: notify.everyone
  data:
    title: Leak Detected
    message: A leak was detected in the laundry
    data:
      push:
        sound:
          name: default
          critical: 1
mode: single
