id: '16105379546964'
alias: 'living_room: notify on noise detected when away'
description: ''
trigger:
- platform: state
  entity_id: binary_sensor.living_room_noise_detected
  from: 'off'
  to: 'on'
condition:
- condition: state
  entity_id: group.all_people
  state: not_home
# Debounce for 5 minutes
- condition: template
  value_template: >-
    {{ (now() - state_attr('automation.living_room_notify_on_noise_detected_when_away','last_triggered')).total_seconds() > 60 * 5 }}
- condition: template
  value_template: |
    {{ is_state('timer.living_room_noise_notification_snooze_timer', 'idle') }}
action:
- service: notify.everyone
  data:
    title: Noise Detected
    message: Noise was detected in the living room
    data:
      attachment:
        content-type: jpeg
      push:
        category: camera
        thread-id: noise-detected
      entity_id: camera.living_room
mode: single
