# Seed configuration for the upstairs RAEX roller blinds
# To be fed into generate_esphome_blinds_ha_config.py to generate a
# Home Assistant compatible package for sending codes via ESPHome custom component
# See: home-assistant/313a/esphome/raex_blind_tx.h
---
tx_device: rf_controller
blinds:
  - name: Bedroom Screen
    remote: 40
    channel: 1
  - name: Bedroom Blockout
    remote: 40
    channel: 2
  - name: Study Screen
    remote: 40
    channel: 3
  - name: Study Blockout
    remote: 40
    channel: 4
  - name: Kitchen Screen
    remote: 40
    channel: 5
  - name: Kitchen Blockout
    remote: 40
    channel: 6
  - name: Living Right Screen
    remote: 41
    channel: 1
  - name: Living Right Blockout
    remote: 41
    channel: 2
  - name: Living Left Blockout
    remote: 40
    channel: 8
  - name: Living Side Blockout
    remote: 40
    channel: 9
