trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
  - job: 'hass_check_config_313a'
    displayName: '[hass] check config: 313a'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.9'
          addToPath: true
          architecture: 'x64'
      - script: |
          ./home-assistant/tools/test_config.sh 313a
        displayName: '[hass] check config: 313a'
  - job: 'hass_check_config_mpl'
    displayName: '[hass] check config: mpl'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.9'
          addToPath: true
          architecture: 'x64'
      - script: |
          ./home-assistant/tools/test_config.sh mpl
        displayName: '[hass] check config: mpl'
  - job: 'hass_check_config_mpl'
    displayName: '[hass] lint and test appdaemon: 313a'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.9'
          addToPath: true
          architecture: 'x64'
      - script: |
          cd ./home-assistant/313a/appdaemon
          black --check .
          flake8
          pytest
        displayName: '[hass] lint and test appdaemon: 313a'