binary_sensor:
  - platform: template
    sensors:
      air_conditioner_power:
        friendly_name: "Air Conditioner Power"
        value_template: |
          {{ states('sensor.air_conditioning_power')|float >= 25 }}
