binary_sensor:
  - platform: template
    sensors:
      heat_transfer_fan_desired_state:
        friendly_name: "Heat Transfer Fan Desired State"
        value_template: |
          {{ 
            (is_state('binary_sensor.study_door_contact', 'on') or is_state('binary_sensor.kates_study_door_contact', 'on'))
            and 
            (is_state('climate.hallway', 'heat') or 
            is_state('climate.hallway', 'cool') or
            is_state('climate.hallway', 'heat_cool') or 
            is_state('climate.hallway', 'dry') or
            is_state('climate.hallway', 'fan_only'))
          }}

sensor:
  - platform: template
    sensors:
      air_conditioner_combined_power:
        friendly_name: "Air Conditioner Combined Power"
        unit_of_measurement: "W"
        availability_template: >
          {{ has_value('sensor.air_conditioning_power') and has_value('sensor.heat_transfer_current_consumption') }}
        value_template: >
          {{
            (states('sensor.air_conditioning_power') | float(0)) +
            (states('sensor.heat_transfer_current_consumption') | float(0))
          }}
