binary_sensor:
  - platform: template
    sensors:
      heat_transfer_fan_desired_state:
        friendly_name: "Heat Transfer Fan Desired State"
        value_template: |
          {{ 
            (is_state('binary_sensor.study_door_contact', 'on') or is_state('binary_sensor.kates_study_door_contact', 'on'))
            and 
            (is_state('climate.hallway', 'heat') or 
            is_state('climate.hallway', 'cool') or
            is_state('climate.hallway', 'heat_cool') or 
            is_state('climate.hallway', 'dry') or
            is_state('climate.hallway', 'fan_only'))
          }}
