sensor:
  platform: template
  sensors:
    comms_cabinet_plug_power:
      friendly_name: Comms Cabinet Power
      unit_of_measurement: Watts
      value_template: "{{ state_attr('switch.comms_cabinet_plug', 'current_power_w') }}"
    comms_cabinet_plug_current:
      friendly_name: Comms Cabinet Current
      unit_of_measurement: Amps
      value_template: "{{ state_attr('switch.comms_cabinet_plug', 'current_a') }}"
    comms_cabinet_plug_voltage:
      friendly_name: Comms Cabinet Voltage
      unit_of_measurement: Volts
      value_template: "{{ state_attr('switch.comms_cabinet_plug', 'voltage') }}"
    comms_cabinet_plug_today_energy:
      friendly_name: Comms Cabinet Today Energy
      unit_of_measurement: kWh
      value_template: "{{ state_attr('switch.comms_cabinet_plug', 'today_energy_kwh') }}"
