ffmpeg:
camera:
  - platform: ffmpeg
    name: Dog Cam
    input: rtsp://192.168.2.82:8554/unicast

binary_sensor:
  - platform: ffmpeg_noise
    name: Dog Cam Noise Detected
    input: rtsp://192.168.2.82:8554/unicast
    extra_arguments: -nostats
    peak: -24

timer:
  camera_noise_notification_snooze_timer:
    duration: "00:00:00"

switch:
  - platform: command_line
    switches:
      dog_cam_night_mode:
        friendly_name: "Dog Cam Night Mode"
        command_state: "/usr/bin/curl -k -X GET 'https://192.168.2.82/cgi-bin/ui_live.cgi?cmd=status_all' | grep ^night_mode | cut -d: -f2"
        command_on: "/usr/bin/curl -k -X GET 'https://192.168.2.82/cgi-bin/ui_live.cgi?cmd=night_mode&action=on'"
        command_off: "/usr/bin/curl -k -X GET 'https://192.168.2.82/cgi-bin/ui_live.cgi?cmd=night_mode&action=off'"
        value_template: '{{ value == "ON" }}'
