binary_sensor:
  platform: template
  sensors:
    dryer:
      friendly_name: "Dryer"
      value_template: >-
        {{ states('sensor.dryer_current_consumption')|float > 5 }}
      icon_template: "mdi:tumble-dryer"
      delay_on: 2
      delay_off: 5
