sensor:
  - platform: command_line
    name: "CPU Temperature"
    command: "ssh -i /config/ssh/id_rsa -o StrictHostKeyChecking=no svc@192.168.2.9 -t 'cat /sys/class/thermal/thermal_zone2/temp'"
    unit_of_measurement: "°C"
    scan_interval: 300
    value_template: "{{ (value | multiply(0.001)) | round(0) }}"
