binary_sensor:
  - platform: template
    sensors:
      internal_motion_occupancy:
        value_template: >
          {{
            is_state('binary_sensor.living_room_motion_occupancy', 'on') or
            is_state('binary_sensor.hallway_motion_occupancy', 'on') or
            is_state('binary_sensor.study_motion_occupancy', 'on') or
            is_state('binary_sensor.kitchen_motion_occupancy', 'on')
          }}

sensor:
  - platform: history_stats
    name: Internal Motion Occupancy Since Dawn
    entity_id: binary_sensor.internal_motion_occupancy
    state: "on"
    type: count
    # Conditional hack to avoid boot race condition when next_dawn is None...
    start: >
      {% if state_attr('sun.sun', 'next_dawn') %}
      {{ state_attr('sun.sun', 'next_dawn') | as_datetime | as_local - timedelta(days=1) }}
      {% else %}
      {{ now() }}
      {% endif %}
    end: "{{ now() }}"
