ffmpeg:
camera:
  - platform: ffmpeg
    name: Living Room
    input: rtsp://192.168.2.91:554/live0

binary_sensor:
  - platform: ffmpeg_noise
    name: Living Room Noise Detected
    input: rtsp://192.168.2.91:554/live0
    extra_arguments: "-nostats"
    peak: -24

timer:
  living_room_camera_noise_notification_snooze_timer:
    duration: "00:00:00"

automation:
  - id: '1619609816687'
    alias: 'living_room camera: restart ffmpeg on unavailable'
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.living_room_noise_detected
      to: unavailable
      for: 00:05:00
    condition: []
    action:
    - service: ffmpeg.restart
      data:
        entity_id: binary_sensor.living_room_noise_detected
    # Debounce for 15 minutes
    - delay: 00:15:00
    mode: single
