binary_sensor:
  platform: template
  sensors:
    living_room_repeater_online:
      friendly_name: "Living Room Repeater Online"
      value_template: >-
        {% set last_updated = states.sensor.living_room_repeater_linkquality.last_updated %}
        {% set last_seen = state_attr('sensor.living_room_repeater_linkquality', 'last_seen') | as_datetime %}
        {% set last_change = max(last_updated, last_seen) %}
        {{ (now() - last_change) < timedelta(hours=4) }}
      icon_template: "mdi:access-point"
