input_boolean:
  osmo_toggle_clean_all_areas:
    name: "All Areas"
    icon: "mdi:home-outline"
  osmo_clean_living_room:
    name: "Living Room"
    icon: "mdi:silverware-fork-knife"
  osmo_clean_kitchen:
    name: "Kitchen"
    icon: "mdi:stove"
  osmo_clean_lounge:
    name: "Lounge"
    icon: "mdi:television"
  osmo_clean_laundry:
    name: "Laundry"
    icon: "mdi:washing-machine"
  osmo_clean_bathroom:
    name: "Bathroom"
    icon: "mdi:bathtub"
  osmo_clean_hallway:
    name: "Hallway"
    icon: "mdi:walk"
  osmo_clean_bedroom:
    name: "Bedroom"
    icon: "mdi:bed"
  osmo_clean_guest_bedroom:
    name: "Guest Bedroom"
    icon: "mdi:bed"
  osmo_clean_study:
    name: "Study"
    icon: "mdi:desk"

input_datetime:
  osmo_last_clean:
    name: "Osmo Last Clean"
    has_date: true
    has_time: true
  osmo_last_clean_living_room:
    name: "Living Room Last Cleaned At"
    has_date: true
    has_time: true
  osmo_last_clean_kitchen:
    name: "Kitchen Last Cleaned At"
    has_date: true
    has_time: true
  osmo_last_clean_lounge:
    name: "Lounge Last Cleaned At"
    has_date: true
    has_time: true
  osmo_last_clean_laundry:
    name: "Laundry Last Cleaned At"
    has_date: true
    has_time: true
  osmo_last_clean_bathroom:
    name: "Bathroom Last Cleaned At"
    has_date: true
    has_time: true
  osmo_last_clean_hallway:
    name: "Hallway Last Cleaned At"
    has_date: true
    has_time: true
  osmo_last_clean_bedroom:
    name: "Bedroom Last Cleaned At"
    has_date: true
    has_time: true
  osmo_last_clean_guest_bedroom:
    name: "Gues Bedroom Last Cleaned At"
    has_date: true
    has_time: true
  osmo_last_clean_study:
    name: "Study Last Cleaned At"
    has_date: true
    has_time: true

input_select:
  osmo_num_passes:
    name: "Number of Passes"
    options:
      - One
      - Two
      - Three
      - Four
  osmo_vacuum_power:
    name: "Vacuum Power"
    options:
      - Quiet
      - Standard
      - Max
      - Max+
  osmo_water_flow:
    name: "Water Flow"
    options:
      - Low
      - Medium
      - High
      - Ultra High

template:
  - sensor:
      - name: "Osmo Selected Rooms"
        unique_id: osmo_selected_rooms_with_truedetect
        state: >-
          {%- set rooms=
            [
              ('input_boolean.osmo_clean_living_room', 2),
              ('input_boolean.osmo_clean_lounge', 7),
              ('input_boolean.osmo_clean_laundry', 6),
              ('input_boolean.osmo_clean_bathroom', 5),
              ('input_boolean.osmo_clean_hallway', 1),
              ('input_boolean.osmo_clean_bedroom', 4),
              ('input_boolean.osmo_clean_guest_bedroom', 0),
              ('input_boolean.osmo_clean_study', 3),
            ]
          -%}
          [
          {%- for entity, room_id in rooms if is_state(entity, 'on') -%}
            {{-  room_id -}}{% if not loop.last %}, {% endif %}
          {%- endfor %}
          ]
      - unique_id: osmo_selected_rooms_without_truedetect
        name: "Osmo Selected Rooms (Without TrueDetect)"
        state: >-
          {%- set rooms=
            [
              ('input_boolean.osmo_clean_kitchen', 8),
            ]
          -%}
          [
          {%- for entity, room_id in rooms if is_state(entity, 'on') -%}
            {{-  room_id -}}{% if not loop.last %}, {% endif %}
          {%- endfor %}
          ]
      - unique_id: osmo_last_clean_living_room_pretty
        state: '{{ strptime(states("input_datetime.osmo_last_clean_living_room"), "%Y-%m-%d %H:%M:%S").strftime("%A") }}'
      - unique_id: osmo_last_clean_kitchen_pretty
        state: '{{ strptime(states("input_datetime.osmo_last_clean_kitchen"), "%Y-%m-%d %H:%M:%S").strftime("%A") }}'
      - unique_id: osmo_last_clean_lounge_pretty
        state: '{{ strptime(states("input_datetime.osmo_last_clean_lounge"), "%Y-%m-%d %H:%M:%S").strftime("%A") }}'
      - unique_id: osmo_last_clean_laundry_pretty
        state: '{{ strptime(states("input_datetime.osmo_last_clean_laundry"), "%Y-%m-%d %H:%M:%S").strftime("%A") }}'
      - unique_id: osmo_last_clean_bathroom_pretty
        state: '{{ strptime(states("input_datetime.osmo_last_clean_bathroom"), "%Y-%m-%d %H:%M:%S").strftime("%A") }}'
      - unique_id: osmo_last_clean_hallway_pretty
        state: '{{ strptime(states("input_datetime.osmo_last_clean_hallway"), "%Y-%m-%d %H:%M:%S").strftime("%A") }}'
      - unique_id: osmo_last_clean_bedroom_pretty
        state: '{{ strptime(states("input_datetime.osmo_last_clean_bedroom"), "%Y-%m-%d %H:%M:%S").strftime("%A") }}'
      - unique_id: osmo_last_clean_guest_bedroom_pretty
        state: '{{ strptime(states("input_datetime.osmo_last_clean_guest_bedroom"), "%Y-%m-%d %H:%M:%S").strftime("%A") }}'
      - unique_id: osmo_last_clean_study_pretty
        state: '{{ strptime(states("input_datetime.osmo_last_clean_study"), "%Y-%m-%d %H:%M:%S").strftime("%A") }}'

automation:
  - id: "osmo_toggle_all_areas_on"
    alias: "osmo: toggle all areas on"
    description: ""
    trigger:
      - platform: state
        entity_id: input_boolean.osmo_toggle_clean_all_areas
        from: "off"
        to: "on"
    condition: []
    action:
      - service: input_boolean.turn_on
        target:
          entity_id:
            - input_boolean.osmo_clean_living_room
            - input_boolean.osmo_clean_kitchen
            - input_boolean.osmo_clean_lounge
            - input_boolean.osmo_clean_laundry
            - input_boolean.osmo_clean_bathroom
            - input_boolean.osmo_clean_hallway
            - input_boolean.osmo_clean_bedroom
            - input_boolean.osmo_clean_guest_bedroom
            - input_boolean.osmo_clean_study
    mode: single

  - id: "osmo_toggle_all_areas_backward"
    alias: "osmo: toggle all areas backward"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - input_boolean.osmo_clean_living_room
          - input_boolean.osmo_clean_kitchen
          - input_boolean.osmo_clean_lounge
          - input_boolean.osmo_clean_laundry
          - input_boolean.osmo_clean_bathroom
          - input_boolean.osmo_clean_hallway
          - input_boolean.osmo_clean_bedroom
          - input_boolean.osmo_clean_guest_bedroom
          - input_boolean.osmo_clean_study
        from: "on"
        to: "off"
    condition: []
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.osmo_toggle_clean_all_areas
    mode: single

  - id: "osmo_set_water_flow"
    alias: "osmo: set water flow"
    description: ""
    trigger:
      - platform: state
        entity_id: input_select.osmo_water_flow
    condition: []
    action:
      - service: vacuum.send_command
        target:
          entity_id: vacuum.osmo
        data:
          command: set_water_level
          params:
            water_level: >
              {{ {'Low': 1, 'Medium': 2, 'High': 3, 'Ultra High': 4 }.get(states('input_select.osmo_water_flow')) }}
    mode: single

  - id: "osmo_set_vacuum_power"
    alias: "osmo: set vacuum power"
    description: ""
    trigger:
      - platform: state
        entity_id: input_select.osmo_vacuum_power
    condition: []
    action:
      - service: vacuum.set_fan_speed
        data:
          fan_speed: "{{ states('input_select.osmo_vacuum_power') }}"
        target:
          entity_id: vacuum.osmo
    mode: single

  - id: "osmo_set_num_passes"
    alias: "osmo: set num passes"
    description: ""
    trigger:
      - platform: state
        entity_id: input_select.osmo_num_passes
    condition: []
    action:
      - service: vacuum.send_command
        target:
          entity_id: vacuum.osmo
        data:
          command: set_clean_count
          params:
            clean_count: >
              {{ {'One': 1, 'Two': 2, 'Three': 3, 'Four': 4 }.get(states('input_select.osmo_num_passes')) }}
    mode: single

  - id: "osmo_update_water_flow_input"
    alias: "osmo: update water flow input select"
    description: ""
    trigger:
      - platform: state
        entity_id: vacuum.osmo
        attribute: water_level
      - platform: homeassistant
        event: start
    condition: []
    action:
      - service: input_select.select_option
        target:
          entity_id: input_select.osmo_water_flow
        data:
          option: >
            {{ state_attr('input_select.osmo_water_flow', 'options')[state_attr('vacuum.osmo', 'water_level') - 1] }}
    mode: single

  - id: "osmo_update_vacuum_power_input"
    alias: "osmo: update vacuum power input select"
    description: ""
    trigger:
      - platform: state
        entity_id: vacuum.osmo
        attribute: vacuum_speed
      - platform: homeassistant
        event: start
    condition: []
    action:
      - service: input_select.select_option
        target:
          entity_id: input_select.osmo_vacuum_power
        data:
          option: >
            {{ state_attr('input_select.osmo_vacuum_power', 'options')[state_attr('vacuum.osmo', 'vacuum_speed') - 1] }}
    mode: single

  - id: "osmo_update_num_passes_input"
    alias: "osmo: update num passes input select"
    description: ""
    trigger:
      - platform: state
        entity_id: vacuum.osmo
        attribute: clean_count
      - platform: homeassistant
        event: start
    condition: []
    action:
      - service: input_select.select_option
        target:
          entity_id: input_select.osmo_num_passes
        data:
          option: >
            {{ state_attr('input_select.osmo_num_passes', 'options')[state_attr('vacuum.osmo', 'clean_count') - 1] }}
    mode: single

script:
  osmo_cancel_cleaning:
    alias: "osmo: cancel cleaning"
    mode: single
    icon: mdi:stop-circle
    sequence:
      - service: script.turn_off
        data: {}
        target:
          entity_id: script.osmo_clean_selected_rooms
      - service: vacuum.return_to_base
        target:
          entity_id: vacuum.osmo
  osmo_clean_living_area:
    alias: "osmo: clean living area"
    mode: single
    icon: mdi:broom
    sequence:
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id:
            - input_boolean.osmo_clean_living_room
            - input_boolean.osmo_clean_lounge
            - input_boolean.osmo_clean_kitchen
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id:
            - input_boolean.osmo_clean_bedroom
            - input_boolean.osmo_clean_guest_bedroom
            - input_boolean.osmo_clean_study
            - input_boolean.osmo_clean_bathroom
            - input_boolean.osmo_clean_laundry
            - input_boolean.osmo_clean_hallway
      - service: switch.turn_on
        target:
          entity_id: switch.osmo_cleaning_preference
      - service: script.osmo_clean_selected_rooms
        data: {}
  osmo_clean_bedrooms:
    alias: "osmo: clean bedrooms"
    mode: single
    icon: mdi:broom
    sequence:
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id:
            - input_boolean.osmo_clean_bedroom
            - input_boolean.osmo_clean_guest_bedroom
            - input_boolean.osmo_clean_study
            - input_boolean.osmo_clean_hallway
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id:
            - input_boolean.osmo_clean_living_room
            - input_boolean.osmo_clean_lounge
            - input_boolean.osmo_clean_kitchen
            - input_boolean.osmo_clean_bathroom
            - input_boolean.osmo_clean_laundry
      - service: switch.turn_on
        target:
          entity_id: switch.osmo_cleaning_preference
      - service: script.osmo_clean_selected_rooms
        data: {}
  osmo_quick_clean:
    alias: "osmo: quick clean"
    mode: single
    icon: mdi:broom
    sequence:
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id:
            - input_boolean.osmo_clean_bedroom
            - input_boolean.osmo_clean_study
            - input_boolean.osmo_clean_guest_bedroom
            - input_boolean.osmo_clean_bathroom
            - input_boolean.osmo_clean_hallway
            - input_boolean.osmo_clean_living_room
            - input_boolean.osmo_clean_lounge
            - input_boolean.osmo_clean_kitchen
            - input_boolean.osmo_clean_laundry
      - service: switch.turn_off
        target:
          entity_id: switch.osmo_cleaning_preference
      - service: input_select.select_option
        data:
          option: One
        target:
          entity_id: input_select.osmo_num_passes
      - service: input_select.select_option
        data:
          option: Standard
        target:
          entity_id: input_select.osmo_vacuum_power
      - service: input_select.select_option
        data:
          option: Low
        target:
          entity_id: input_select.osmo_water_flow
      - service: script.osmo_clean_selected_rooms
        data: {}
  osmo_auto_clean:
    alias: "osmo: auto clean"
    mode: single
    icon: mdi:broom
    sequence:
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id:
            - input_boolean.osmo_clean_bedroom
            - input_boolean.osmo_clean_study
            - input_boolean.osmo_clean_guest_bedroom
            - input_boolean.osmo_clean_bathroom
            - input_boolean.osmo_clean_hallway
            - input_boolean.osmo_clean_living_room
            - input_boolean.osmo_clean_lounge
            - input_boolean.osmo_clean_kitchen
            - input_boolean.osmo_clean_laundry
      - service: switch.turn_on
        target:
          entity_id: switch.osmo_cleaning_preference
      - service: script.osmo_clean_selected_rooms
        data: {}
  osmo_deep_clean:
    alias: "osmo: deep clean"
    mode: single
    icon: mdi:broom
    sequence:
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id:
            - input_boolean.osmo_clean_bedroom
            - input_boolean.osmo_clean_study
            - input_boolean.osmo_clean_guest_bedroom
            - input_boolean.osmo_clean_bathroom
            - input_boolean.osmo_clean_hallway
            - input_boolean.osmo_clean_living_room
            - input_boolean.osmo_clean_lounge
            - input_boolean.osmo_clean_kitchen
            - input_boolean.osmo_clean_laundry
      - service: switch.turn_off
        target:
          entity_id: switch.osmo_cleaning_preference
      - service: input_select.select_option
        data:
          option: Three
        target:
          entity_id: input_select.osmo_num_passes
      - service: input_select.select_option
        data:
          option: Max
        target:
          entity_id: input_select.osmo_vacuum_power
      - service: input_select.select_option
        data:
          option: Low
        target:
          entity_id: input_select.osmo_water_flow
      - service: script.osmo_clean_selected_rooms
        data: {}
  osmo_summon:
    alias: "osmo: summon"
    mode: single
    icon: mdi:broom
    sequence:
      - service: vacuum.stop
        target:
          entity_id: vacuum.osmo
      - service: vacuum.send_command
        target:
          entity_id: vacuum.osmo
        data:
          command: clean_custom
          params:
            custom_area: "-1327,6254,-1051,5978"
      - delay: 00:00:10
      - service: vacuum.stop
        target:
          entity_id: vacuum.osmo
  osmo_clean_selected_rooms:
    alias: "osmo: clean selected rooms"
    mode: single
    icon: mdi:broom
    sequence:
      - service: vacuum.stop
        target:
          entity_id: vacuum.osmo
      - choose:
          - conditions:
              - condition: template
                value_template: >-
                  {{ states('sensor.osmo_selected_rooms_with_truedetect')|from_json|length > 0 }}
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: switch.osmo_truedetect
              - delay: 00:00:05
              - service: vacuum.send_command
                target:
                  entity_id: vacuum.osmo
                data:
                  command: clean_areas
                  params:
                    area_ids: >-
                      {{ states('sensor.osmo_selected_rooms_with_truedetect')|from_json }}
        default: []
      - choose:
          - conditions:
              - condition: template
                value_template: >-
                  {{
                    states('sensor.osmo_selected_rooms_with_truedetect')|from_json|length > 0 and
                    states('sensor.osmo_selected_rooms_without_truedetect')|from_json|length > 0
                  }}
            sequence:
              - wait_for_trigger:
                  - platform: state
                    entity_id: vacuum.osmo
                    from: cleaning
                    to: returning
                timeout: 01:30:00
                continue_on_timeout: false
              - service: vacuum.stop
                target:
                  entity_id: vacuum.osmo
              - delay: 00:00:02
      - choose:
          - conditions:
              - condition: template
                value_template: >-
                  {{ states('sensor.osmo_selected_rooms_without_truedetect')|from_json|length > 0 }}
            sequence:
              - service: switch.turn_off
                target:
                  entity_id: switch.osmo_truedetect
              - delay: 00:00:05
              - service: vacuum.send_command
                target:
                  entity_id: vacuum.osmo
                data:
                  command: clean_areas
                  params:
                    area_ids: >-
                      {{ states('sensor.osmo_selected_rooms_without_truedetect')|from_json }}
        default: []
      - wait_for_trigger:
          - platform: state
            entity_id: vacuum.osmo
            from: cleaning
            to: returning
        timeout: 01:00:00
        continue_on_timeout: false
      - service: input_datetime.set_datetime
        data:
          timestamp: "{{ now().timestamp() }}"
        target:
          entity_id: >
            {%- set rooms=
              [
                'living_room',
                'kitchen',
                'lounge',
                'laundry',
                'bathroom',
                'hallway',
                'bedroom',
                'guest_bedroom',
                'study',                
              ]
            -%}
            input_datetime.osmo_last_clean
            {% for room_slug in rooms if is_state('input_boolean.osmo_clean_' + room_slug, 'on') -%}
            , input_datetime.osmo_last_clean_{{  room_slug }}
            {% endfor -%}
