media_player:
  - platform: samsungtv_tizen
    name: "Samsung Smart TV"
    host: "192.168.2.132"
    mac: !secret samsung_smart_tv_mac
    update_method: websockets
    # Avoid using SmartThings API as it makes TV uncontrollable
    # api_key: !secret samsung_smart_tv_api_key
    # device_id: !secret samsung_smart_tv_device_id
    app_list: >-
      {
        "7 Plus": "icp4AvUPiA.7plus",
        "Netflix": "11101200001",
        "Plex": "3201512006963",
        "Spotify": "3201606009684",
        "Stan": "73iTZRTc34.Stan",
        "Steam Link": "vIutycUzou.SteamLink",
        "YouTube": "111299001912"
      }
    channel_list: >-
      {
        "ABCTV HD": "20",
        "ABC News 24": "24",
        "SBS HD": "30",
        "Seven HD": "70",
        "Nine HD": "90",
        "10 HD": "13"
      }

sensor:
  - platform: template
    sensors:
      samsung_smart_tv_source:
        friendly_name: "Samsung Smart TV Source"
        value_template: >-
          {{ state_attr('media_player.samsung_smart_tv','source') }}

automation:
  - id: "682B367539FB"
    alias: "homekit remote: media key arrow_up"
    description: ""
    trigger:
      - event_type: homekit_tv_remote_key_pressed
        platform: event
        event_data:
          entity_id: media_player.samsung_smart_tv
          key_name: arrow_up
    condition: []
    action:
      - service: media_player.play_media
        data:
          entity_id: media_player.samsung_smart_tv
          media_content_type: send_key
          media_content_id: KEY_UP
  - id: "B07D24A1E86E"
    alias: "homekit remote: media key arrow_down"
    description: ""
    trigger:
      - event_type: homekit_tv_remote_key_pressed
        platform: event
        event_data:
          entity_id: media_player.samsung_smart_tv
          key_name: arrow_down
    condition: []
    action:
      - service: media_player.play_media
        data:
          entity_id: media_player.samsung_smart_tv
          media_content_type: send_key
          media_content_id: KEY_DOWN
  - id: "C89C74C0D202"
    alias: "homekit remote: media key arrow_left"
    description: ""
    trigger:
      - event_type: homekit_tv_remote_key_pressed
        platform: event
        event_data:
          entity_id: media_player.samsung_smart_tv
          key_name: arrow_left
    condition: []
    action:
      - service: media_player.play_media
        data:
          entity_id: media_player.samsung_smart_tv
          media_content_type: send_key
          media_content_id: KEY_LEFT
  - id: "940199676C17"
    alias: "homekit remote: media key arrow_right"
    description: ""
    trigger:
      - event_type: homekit_tv_remote_key_pressed
        platform: event
        event_data:
          entity_id: media_player.samsung_smart_tv
          key_name: arrow_right
    condition: []
    action:
      - service: media_player.play_media
        data:
          entity_id: media_player.samsung_smart_tv
          media_content_type: send_key
          media_content_id: KEY_RIGHT
  - id: "8E9E5B27D4BE"
    alias: "homekit remote: media key back"
    description: ""
    trigger:
      - event_type: homekit_tv_remote_key_pressed
        platform: event
        event_data:
          entity_id: media_player.samsung_smart_tv
          key_name: back
    condition: []
    action:
      - service: media_player.play_media
        data:
          entity_id: media_player.samsung_smart_tv
          media_content_type: send_key
          media_content_id: KEY_RETURN
  - id: "25B3FEE288AD"
    alias: "homekit remote: media key select"
    description: ""
    trigger:
      - event_type: homekit_tv_remote_key_pressed
        platform: event
        event_data:
          entity_id: media_player.samsung_smart_tv
          key_name: select
    condition: []
    action:
      - service: media_player.play_media
        data:
          entity_id: media_player.samsung_smart_tv
          media_content_type: send_key
          media_content_id: KEY_ENTER
  - id: "4AD260B62D6D"
    alias: "homekit remote: media key information"
    description: ""
    trigger:
      - event_type: homekit_tv_remote_key_pressed
        platform: event
        event_data:
          entity_id: media_player.samsung_smart_tv
          key_name: information
    condition: []
    action:
      - service: media_player.play_media
        data:
          entity_id: media_player.samsung_smart_tv
          media_content_type: send_key
          media_content_id: KEY_HOME
