sensor:
  platform: template
  sensors:
    study_plug_power:
      friendly_name: Study Power
      unit_of_measurement: Watts
      value_template: "{{ state_attr('switch.study_plug', 'current_power_w') }}"
    study_plug_current:
      friendly_name: Study Current
      unit_of_measurement: Amps
      value_template: "{{ state_attr('switch.study_plug', 'current_a') }}"
    study_plug_voltage:
      friendly_name: Study Voltage
      unit_of_measurement: Volts
      value_template: "{{ state_attr('switch.study_plug', 'voltage') }}"
    study_plug_today_energy:
      friendly_name: Study Today Energy
      unit_of_measurement: kWh
      value_template: "{{ state_attr('switch.study_plug', 'today_energy_kwh') }}"
