sensor:
  platform: template
  sensors:
    washing_machine_power:
      friendly_name: Washing Machine Power
      unit_of_measurement: Watts
      value_template: "{{ state_attr('switch.washing_machine', 'current_power_w') }}"
    washing_machine_current:
      friendly_name: Washing Machine Current
      unit_of_measurement: Amps
      value_template: "{{ state_attr('switch.washing_machine', 'current_a') }}"
    washing_machine_voltage:
      friendly_name: Washing Machine Voltage
      unit_of_measurement: Volts
      value_template: "{{ state_attr('switch.washing_machine', 'voltage') }}"
    washing_machine_today_energy:
      friendly_name: Washing Machine Today Energy
      unit_of_measurement: kWh
      value_template: "{{ state_attr('switch.washing_machine', 'today_energy_kwh') }}"

binary_sensor:
  platform: template
  sensors:
    washing_machine:
      friendly_name: "Washing Machine"
      value_template: >-
        {{ states('sensor.washing_machine_power')|float > 2 }}
      icon_template: "mdi:washing-machine"
      delay_on: 2
      delay_off: 5
