sensor:
  platform: template
  sensors:
    washing_machine_power:
      friendly_name: Washing Machine Power
      unit_of_measurement: Watts
      value_template: "{{ state_attr('switch.washing_machine', 'current_power_w') }}"
    washing_machine_current:
      friendly_name: Washing Machine Current
      unit_of_measurement: Amps
      value_template: "{{ state_attr('switch.washing_machine', 'current_a') }}"
    washing_machine_voltage:
      friendly_name: Washing Machine Voltage
      unit_of_measurement: Volts
      value_template: "{{ state_attr('switch.washing_machine', 'voltage') }}"
    washing_machine_today_energy:
      friendly_name: Washing Machine Today Energy
      unit_of_measurement: kWh
      value_template: "{{ state_attr('switch.washing_machine', 'today_energy_kwh') }}"

binary_sensor:
  platform: template
  sensors:
    washing_machine:
      friendly_name: "Washing Machine"
      value_template: >-
        {{ states('sensor.washing_machine_power')|float > 2 }}
      icon_template: "mdi:washing-machine"
      delay_on: 2
      delay_off: 5

input_boolean:
  washing_completed_unacknowledged:

automation:
  - id: '1577766070397'
    alias: when washing machine completed, send notification
    description: ''
    trigger:
      - entity_id: binary_sensor.washing_machine
        from: 'on'
        platform: state
        to: 'off'
    condition: []
    action:
      - data:
          data:
            apns_headers:
              apns-collapse-id: washing-complete
            push:
              thread-id: washing-complete
          message: The washing machine has completed. Time to hang out the clothes.
          title: Washing Complete!
        service: notify.everyone
  - id: '1592101514693'
    alias: when washing machine completed, broadcast
    description: ''
    trigger:
      - entity_id: binary_sensor.washing_machine
        from: 'on'
        platform: state
        to: 'off'
    condition:
      - condition: state
        entity_id: group.all_people
        state: home
    action:
      - service: media_player.volume_set
        entity_id:
          - media_player.kitchen_speaker
          - media_player.living_room_speaker
        data:
          volume_level: 0.5
      - service: tts.google_translate_say
        entity_id:
          - media_player.kitchen_speaker
          - media_player.living_room_speaker
        data:
          message: The washing machine has finished!
  - id: '1592102651795'
    alias: when washing completed, whilst away, notify when arriving home
    description: ''
    trigger:
      - entity_id: binary_sensor.washing_machine
        from: 'on'
        platform: state
        to: 'off'
    condition:
      - condition: state
        entity_id: group.all_people
        state: not_home
    action:
      - wait_template: '{{ is_state("group.all_people", "home") }}'
        timeout: '24:00:00'
      - delay: 00:05:00
      - service: media_player.volume_set
        entity_id:
          - media_player.kitchen_speaker
          - media_player.living_room_speaker
        data:
          volume_level: 0.5
      - service: tts.google_translate_say
        entity_id:
          - media_player.kitchen_speaker
          - media_player.living_room_speaker
        data:
          message: The washing machine finished whilst away
