binary_sensor:
  platform: template
  sensors:
    washing_machine:
      friendly_name: "Washing Machine"
      value_template: >-
        {{ states('sensor.washing_machine_current_consumption')|float > 5 }}
      icon_template: "mdi:washing-machine"
      delay_on: 2
      delay_off: 5
