id: '1630232548361'
alias: 'living room camera: turn on camera when away'
description: ''
mode: single
trigger:
- platform: state
  entity_id: group.all_people
  to: not_home
condition: []
action:
- service: switch.turn_on
  target:
    entity_id: switch.living_room_camera_power
