id: "1630232825286"
alias: "living room camera: turn on camera for 10 mins when front door opens"
description: Used to trigger camera to record until presence detection kicks in
  (also good to catch any intrusion whilst home)
trigger:
  - platform: state
    entity_id: binary_sensor.front_door
    to: "on"
condition: []
action:
  - service: switch.turn_on
    target:
      entity_id: switch.living_room_camera_power
  - wait_for_trigger:
      - platform: state
        entity_id: group.all_people
        to: not_home
    timeout: 00:10:00
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ not wait.trigger }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: switch.living_room_camera_power
    default: []
mode: restart
