homeassistant:
  customize:
    # Efergy provided sensors
    sensor.efergy_731181:
      friendly_name: Solar Input
      icon: mdi:arrow-left
    sensor.efergy_784242:
      friendly_name: Phase B Load
      icon: mdi:power
    sensor.efergy_786148:
      friendly_name: Phase A/C Load
      icon: mdi:power
    sensor.energy_consumed:
      friendly_name: Energy Consumed Today
      icon: mdi:power

    # Template sensors
    sensor.mains_input:
      icon: mdi:arrow-left
    sensor.mains_output:
      icon: mdi:arrow-right
    sensor.current_load:
      icon: mdi:power
    sensor.current_load_kw:
      icon: mdi:power

sensor:
  # A handful of integration sensors to measure power over time (energy). These
  # are used with the Home Assistant "Energy" dashboard in combination with the
  # utility_meter sensor counterparts.
  - platform: integration
    source: sensor.efergy_731181
    name: "Solar Energy"
  - platform: integration
    source: sensor.efergy_784242
    name: "Phase B Energy"
  - platform: integration
    source: sensor.efergy_786148
    name: "Phase A/C Energy"
  - platform: integration
    source: sensor.mains_input
    name: "Grid Energy Consumed"
  - platform: integration
    source: sensor.mains_output
    name: "Grid Energy Produced"

  - platform: template
    # efergy_784242: Phase B Load
    # efergy_786148: Phase AC Load
    # efergy_731181: Solar Input
    sensors:
      mains_input:
        friendly_name: "Mains Input"
        unit_of_measurement: "W"
        value_template: |
          {% if states.sensor.efergy_784242.state|float > states.sensor.efergy_731181.state|float %}
            {{ states.sensor.efergy_786148.state|float + states.sensor.efergy_784242.state|float - states.sensor.efergy_731181.state|float }}
          {% else %}
            {{ states.sensor.efergy_786148.state|float }}
          {% endif %}

      mains_output:
        friendly_name: "Mains Output"
        unit_of_measurement: "W"
        value_template: |
          {% if states.sensor.efergy_784242.state|float > states.sensor.efergy_731181.state|float %}
            0
          {% else %}
            {{ states.sensor.efergy_731181.state|float - states.sensor.efergy_784242.state|float }}
          {% endif %}

      current_load:
        friendly_name: Current Load
        unit_of_measurement: "W"
        value_template: |
          {{ states("sensor.efergy_784242") | float +  states("sensor.efergy_786148") | float }}

      current_load_kw:
        friendly_name: Current Load
        unit_of_measurement: "kW"
        value_template: |
          {{ states("sensor.current_load")|float / 1000 | round(2) }}

utility_meter:
  # For energy monitoring feature, the integration sensor platform doesn't
  # expose the entities as statistics capable, so we use these.
  solar_energy_meter:
    source: sensor.solar_energy
    cycle: yearly
  phase_b_energy_meter:
    source: sensor.phase_b_energy
    cycle: yearly
  phase_a_c_energy_meter:
    source: sensor.phase_a_c_energy
    cycle: yearly
  grid_consumed_energy_meter:
    source: sensor.grid_energy_consumed
    cycle: yearly
  grid_produced_energy_meter:
    source: sensor.grid_energy_produced
    cycle: yearly
