id: "1605957734652"
alias: "hallway: turn on light on motion detected at night"
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.hallway_motion_occupancy
      - binary_sensor.living_room_motion_occupancy
    from: "off"
    to: "on"
condition:
  - condition: or
    conditions:
      - condition: time
        after: "23:00:00"
      - condition: sun
        before: sunrise
  - condition: state
    entity_id: light.hallway
    state: "off"
  - condition: state
    entity_id: input_boolean.guest_mode
    state: "off"
action:
  - service: light.turn_on
    data:
      brightness_pct: 15
    entity_id: light.hallway
  - wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.internal_motion_occupancy
        from: "on"
        to: "off"
        for: 00:01:00
  - service: light.turn_off
    data: {}
    entity_id: light.hallway
mode: single
