id: "1722943181852"
alias: "hallway ac: turn on at midnight"
description: ""
trigger:
  - platform: time
    at: 02:00:00
    id: turn_on
  - platform: time
    at: 06:00:00
    id: turn_off
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - turn_on
          - condition: state
            entity_id: group.all_people
            state: home
        sequence:
          - metadata: {}
            data:
              hvac_mode: cool
              temperature: 23
            target:
              entity_id: climate.hallway
            action: climate.set_temperature
          - target:
              entity_id: climate.hallway
            data:
              fan_mode: low
            action: climate.set_fan_mode
      - conditions:
          - condition: trigger
            id:
              - turn_off
        sequence:
          - metadata: {}
            data: {}
            target:
              entity_id: climate.hallway
            action: climate.turn_off
mode: single
