id: "1669714700223"
alias: "outdoor: turn xmas lights on at sunset"
description: "outdoor: turn xmas lights on at sunset"
trigger:
  - platform: sun
    event: sunset
    offset: 0
action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.front_christmas_lights
mode: single
