homeassistant:
  customize:
    switch.sprinkle_herbs_power:
      hidden: true
    switch.sprinkle_herbs_trigger:
      hidden: true
    switch.sprinkle_herbs:
      friendly_name: Herbs
    switch.sprinkle_lavender_power:
      hidden: true
    switch.sprinkle_lavender_trigger:
      hidden: true
    switch.sprinkle_lavender:
      friendly_name: Lavender
    switch.sprinkle_upper_lawn_power:
      hidden: true
    switch.sprinkle_upper_lawn_trigger:
      hidden: true
    switch.sprinkle_upper_lawn:
      friendly_name: Upper Lawn
    switch.sprinkle_front_terrace_power:
      hidden: true
    switch.sprinkle_front_terrace_trigger:
      hidden: true
    switch.sprinkle_front_terrace:
      friendly_name: Front Terrace
    switch.sprinkle_front_terrace_recycled_power:
      hidden: true
    switch.sprinkle_front_terrace_recycled_trigger:
      hidden: true
    switch.sprinkle_front_terrace_recycled:
      friendly_name: Front Terrace Recycled
    switch.sprinkle_lower_lawn_power:
      hidden: true
    switch.sprinkle_lower_lawn_trigger:
      hidden: true
    switch.sprinkle_lower_lawn:
      friendly_name: Lower Lawn
    switch.sprinkle_back_yard_power:
      hidden: true
    switch.sprinkle_back_yard_trigger:
      hidden: true
    switch.sprinkle_back_yard:
      friendly_name: Back Yard
    switch.sprinkle_back_yard_recycled_power:
      hidden: true
    switch.sprinkle_back_yard_recycled_trigger:
      hidden: true
    switch.sprinkle_back_yard_recycled:
      friendly_name: Back Yard Recycled
    switch.sprinkle_recycled_pump_power:
      hidden: true
    switch.sprinkle_recycled_pump_trigger:
      hidden: true
    switch.sprinkle_recycled_pump:
      friendly_name: Recycled Pump
    switch.sprinkle_tree_lights:
      friendly_name: Tree Lights
switch:
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_herbs_power
  command_topic: sprinkle/1/set
  state_topic: sprinkle/1
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_herbs_trigger
  command_topic: sprinkle/1/set
  payload_on: ON:600
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_lavender_power
  command_topic: sprinkle/2/set
  state_topic: sprinkle/2
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_lavender_trigger
  command_topic: sprinkle/2/set
  payload_on: ON:600
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_upper_lawn_power
  command_topic: sprinkle/3/set
  state_topic: sprinkle/3
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_upper_lawn_trigger
  command_topic: sprinkle/3/set
  payload_on: ON:600
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_front_terrace_power
  command_topic: sprinkle/4/set
  state_topic: sprinkle/4
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_front_terrace_trigger
  command_topic: sprinkle/4/set
  payload_on: ON:600
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_front_terrace_recycled_power
  command_topic: sprinkle/5/set
  state_topic: sprinkle/5
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_front_terrace_recycled_trigger
  command_topic: sprinkle/5/set
  payload_on: ON:1200
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_lower_lawn_power
  command_topic: sprinkle/6/set
  state_topic: sprinkle/6
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_lower_lawn_trigger
  command_topic: sprinkle/6/set
  payload_on: ON:600
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_back_yard_power
  command_topic: sprinkle/7/set
  state_topic: sprinkle/7
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_back_yard_trigger
  command_topic: sprinkle/7/set
  payload_on: ON:600
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_back_yard_recycled_power
  command_topic: sprinkle/8/set
  state_topic: sprinkle/8
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_back_yard_recycled_trigger
  command_topic: sprinkle/8/set
  payload_on: ON:1200
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_recycled_pump_power
  command_topic: sprinkle/9/set
  state_topic: sprinkle/9
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_recycled_pump_trigger
  command_topic: sprinkle/9/set
  payload_on: ON:1200
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_tree_lights
  icon: mdi:tree
  command_topic: sprinkle/10/set
  state_topic: sprinkle/10
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: template
  switches:
    sprinkle_herbs:
      value_template: "{{ is_state('switch.sprinkle_herbs_power', 'on') }}"
      icon_template: mdi:water
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.sprinkle_herbs_trigger
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.sprinkle_herbs_power
    sprinkle_lavender:
      value_template: "{{ is_state('switch.sprinkle_lavender_power', 'on') }}"
      icon_template: mdi:water
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.sprinkle_lavender_trigger
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.sprinkle_lavender_power
    sprinkle_upper_lawn:
      value_template: "{{ is_state('switch.sprinkle_upper_lawn_power', 'on') }}"
      icon_template: mdi:water
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.sprinkle_upper_lawn_trigger
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.sprinkle_upper_lawn_power
    sprinkle_front_terrace:
      value_template: "{{ is_state('switch.sprinkle_front_terrace_power', 'on') }}"
      icon_template: mdi:water
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.sprinkle_front_terrace_trigger
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.sprinkle_front_terrace_power
    sprinkle_front_terrace_recycled:
      value_template: "{{ is_state('switch.sprinkle_front_terrace_recycled_power',\
        \ 'on') }}"
      icon_template: mdi:water
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.sprinkle_front_terrace_recycled_trigger
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.sprinkle_front_terrace_recycled_power
    sprinkle_lower_lawn:
      value_template: "{{ is_state('switch.sprinkle_lower_lawn_power', 'on') }}"
      icon_template: mdi:water
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.sprinkle_lower_lawn_trigger
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.sprinkle_lower_lawn_power
    sprinkle_back_yard:
      value_template: "{{ is_state('switch.sprinkle_back_yard_power', 'on') }}"
      icon_template: mdi:water
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.sprinkle_back_yard_trigger
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.sprinkle_back_yard_power
    sprinkle_back_yard_recycled:
      value_template: "{{ is_state('switch.sprinkle_back_yard_recycled_power', 'on')\
        \ }}"
      icon_template: mdi:water
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.sprinkle_back_yard_recycled_trigger
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.sprinkle_back_yard_recycled_power
    sprinkle_recycled_pump:
      value_template: "{{ is_state('switch.sprinkle_recycled_pump_power', 'on') }}"
      icon_template: mdi:water
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.sprinkle_recycled_pump_trigger
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.sprinkle_recycled_pump_power

sensor:
  - platform: mqtt
    name: Sprinkle Uptime
    state_topic: sprinkle/uptime
    availability_topic: sprinkle/status
    unit_of_measurement: ms

  - platform: template
    sensors:
      sprinkle_uptime_friendly:
        friendly_name: Sprinkle Uptime
        value_template: >-
          {{(states('sensor.sprinkle_uptime') | int / 1000 / 60) | round(0) }}
        unit_of_measurement: minutes
