- platform: efergy
  app_token: !secret efergy_app_token
  utc_offset: 600
  monitored_variables:
    - type: amount
      period: day
    - type: current_values

- platform: template
  # efergy_784242: Phase B Load
  # efergy_786148: Phase AC Load
  # efergy_731181: Solar Input
  sensors:
    mains_input:
      friendly_name: "Mains Input"
      unit_of_measurement: 'W'
      value_template: |
        {% if states.sensor.efergy_784242.state|float > states.sensor.efergy_731181.state|float %}
          {{ states.sensor.efergy_786148.state|float + states.sensor.efergy_784242.state|float - states.sensor.efergy_731181.state|float }}
        {% else %}
          {{ states.sensor.efergy_786148.state|float }}
        {% endif %}

    mains_output:
      friendly_name: "Mains Output"
      unit_of_measurement: 'W'
      value_template: |
        {% if states.sensor.efergy_784242.state|float > states.sensor.efergy_731181.state|float %}
          0
        {% else %}
          {{ states.sensor.efergy_731181.state|float - states.sensor.efergy_784242.state|float }}
        {% endif %}
