id: '1613560799505'
alias: 'ios: handle living room noise notification snooze timer on app action'
description: ''
trigger:
- platform: event
  event_type: ios.notification_action_fired
  event_data:
    categoryName: CAMERA
condition: []
action:
- service: timer.start
  data:
    duration: |
     {%- if trigger.event.data.actionName == "SNOOZE_15_MIN" -%}
       00:15:00
     {%- elif trigger.event.data.actionName == "SNOOZE_1_HOUR" -%}
       01:00:00
     {%- elif trigger.event.data.actionName == "SNOOZE_4_HOURS" -%}
       04:00:00
     {%- elif trigger.event.data.actionName == "SNOOZE_UNTIL_HOME" -%}
       00:15:00
     {%- endif -%}
  entity_id: timer.living_room_noise_notification_snooze_timer
- choose:
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.actionName == "SNOOZE_UNTIL_HOME" }}'
    sequence:
    - service: timer.pause
      data: {}
      entity_id: timer.living_room_noise_notification_snooze_timer
  default: []
mode: single
