id: "kitchen_tablet_wake_on_front_door_activity"
alias: Wake kitchen tablet on front door activity
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.front_door_doorbell
    from: "off"
    to: "on"
  - platform: state
    entity_id:
      - binary_sensor.front_door_person_detected
    from: "off"
    to: "on"
  - platform: state
    entity_id:
      - binary_sensor.front_yard_right_person_detected
    from: "off"
    to: "on"
  - platform: state
    entity_id:
      - binary_sensor.front_yard_person_detected
    from: "off"
    to: "on"
condition: []
action:
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ states('light.kitchen_tablet_screen') in ['unknown', 'unavailable'] }}
        sequence:
          - service: notify.mobile_app_kates_ipad
            data:
              message: wake
  - wait_template: >
      {{ states('light.kitchen_tablet_screen') not in ['unknown', 'unavailable'] }}
    timeout: "00:00:10"
    continue_on_timeout: true
  - service: light.turn_on
    target:
      entity_id: light.kitchen_tablet_screen
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - service: browser_mod.popup
    data:
      browser_id: browser_mod_f0a0a61b_7f9662df
      size: wide
      timeout: 180000
      title: Front Door
      content:
        show_state: false
        show_name: false
        camera_view: live
        type: picture-entity
        entity: camera.front_door_medium
        name: Front Door
        camera_image: camera.front_door_medium
        tap_action:
          action: none
        hold_action:
          action: none
mode: single
