- platform: mqtt
  name: Sprinkle Uptime
  state_topic: sprinkle/uptime
  availability_topic: sprinkle/status
  unit_of_measurement: ms

- platform: template
  sensors:
    sprinkle_uptime_friendly:
      friendly_name: Sprinkle Uptime
      value_template: >-
        {{states('sensor.sprinkle_uptime') | int / 1000 / 60 }}
