- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_herbs_power
  command_topic: sprinkle/1/set
  state_topic: sprinkle/1
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_herbs_trigger
  command_topic: sprinkle/1/set
  payload_on: ON:600
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_lavender_power
  command_topic: sprinkle/2/set
  state_topic: sprinkle/2
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_lavender_trigger
  command_topic: sprinkle/2/set
  payload_on: ON:600
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_upper_lawn_power
  command_topic: sprinkle/3/set
  state_topic: sprinkle/3
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_upper_lawn_trigger
  command_topic: sprinkle/3/set
  payload_on: ON:600
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_front_terrace_power
  command_topic: sprinkle/4/set
  state_topic: sprinkle/4
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_front_terrace_trigger
  command_topic: sprinkle/4/set
  payload_on: ON:600
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_front_terrace_recycled_power
  command_topic: sprinkle/5/set
  state_topic: sprinkle/5
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_front_terrace_recycled_trigger
  command_topic: sprinkle/5/set
  payload_on: ON:900
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_lower_lawn_power
  command_topic: sprinkle/6/set
  state_topic: sprinkle/6
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_lower_lawn_trigger
  command_topic: sprinkle/6/set
  payload_on: ON:600
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_back_yard_power
  command_topic: sprinkle/7/set
  state_topic: sprinkle/7
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_back_yard_trigger
  command_topic: sprinkle/7/set
  payload_on: ON:600
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_back_yard_recycled_power
  command_topic: sprinkle/8/set
  state_topic: sprinkle/8
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_back_yard_recycled_trigger
  command_topic: sprinkle/8/set
  payload_on: ON:900
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_recycled_pump_power
  command_topic: sprinkle/9/set
  state_topic: sprinkle/9
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_recycled_pump_trigger
  command_topic: sprinkle/9/set
  payload_on: ON:900
  qos: 1
- platform: mqtt
  availability_topic: sprinkle/status
  name: sprinkle_tree_lights
  icon: mdi:tree
  command_topic: sprinkle/10/set
  state_topic: sprinkle/10
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: template
  switches:
    sprinkle_herbs:
      value_template: '{{ states.switch.sprinkle_herbs_power.state }}'
      icon_template: mdi:water
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.sprinkle_herbs_trigger
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.sprinkle_herbs_power
    sprinkle_lavender:
      value_template: '{{ states.switch.sprinkle_lavender_power.state }}'
      icon_template: mdi:water
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.sprinkle_lavender_trigger
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.sprinkle_lavender_power
    sprinkle_upper_lawn:
      value_template: '{{ states.switch.sprinkle_upper_lawn_power.state }}'
      icon_template: mdi:water
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.sprinkle_upper_lawn_trigger
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.sprinkle_upper_lawn_power
    sprinkle_front_terrace:
      value_template: '{{ states.switch.sprinkle_front_terrace_power.state }}'
      icon_template: mdi:water
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.sprinkle_front_terrace_trigger
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.sprinkle_front_terrace_power
    sprinkle_front_terrace_recycled:
      value_template: '{{ states.switch.sprinkle_front_terrace_recycled_power.state
        }}'
      icon_template: mdi:water
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.sprinkle_front_terrace_recycled_trigger
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.sprinkle_front_terrace_recycled_power
    sprinkle_lower_lawn:
      value_template: '{{ states.switch.sprinkle_lower_lawn_power.state }}'
      icon_template: mdi:water
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.sprinkle_lower_lawn_trigger
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.sprinkle_lower_lawn_power
    sprinkle_back_yard:
      value_template: '{{ states.switch.sprinkle_back_yard_power.state }}'
      icon_template: mdi:water
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.sprinkle_back_yard_trigger
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.sprinkle_back_yard_power
    sprinkle_back_yard_recycled:
      value_template: '{{ states.switch.sprinkle_back_yard_recycled_power.state }}'
      icon_template: mdi:water
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.sprinkle_back_yard_recycled_trigger
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.sprinkle_back_yard_recycled_power
    sprinkle_recycled_pump:
      value_template: '{{ states.switch.sprinkle_recycled_pump_power.state }}'
      icon_template: mdi:water
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.sprinkle_recycled_pump_trigger
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.sprinkle_recycled_pump_power
