esphome:
  name: charlotte_ledstrip
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "charlotte_ledstrip"
    password: !secret wifi_fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

output:
  - platform: esp8266_pwm
    pin: 5
    id: 'color_green'
    max_power: 60%
  - platform: esp8266_pwm
    pin: 12
    id: 'color_red'
  - platform: esp8266_pwm
    pin: 13
    id: 'color_blue'
    max_power: 30%
  - platform: esp8266_pwm
    pin: 15
    id: 'color_white'

light:
  - platform: rgbw
    name: "Charlotte LED Strip"
    red: color_red
    green: color_green
    blue: color_blue
    white: color_white
    effects:
      - strobe
      - flicker
      - random