esphome:
  name: outdoor_thermometer
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "outdoor_thermometer"
    password: !secret wifi_fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: dht
    pin: GPIO14
    model: SI7021
    humidity:
      name: "Outdoor Humidity"
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 10
    temperature:
      name: "Outdoor Temperature"
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 10
    update_interval: 30s
