id: '4389479823798'
alias: 'living_room: toggle living room blinds on button hold'
description: ''
trigger:
- platform: state
  entity_id: sensor.living_room_button_click
  to: single
condition: []
action:
- service: cover.toggle
  entity_id: cover.living_room_blinds
mode: single
