id: '1603016384862'
alias: 'living_room: toggle dining table light on button press'
description: ''
trigger:
- platform: state
  entity_id: sensor.living_room_button_click
  to: single
condition: []
action:
- service: light.toggle
  data: {}
  entity_id: light.dining_table
mode: single
