id: "1600953878712"
alias: "bedroom: toggle bedsides on bedside button press"
description: ""
trigger:
  - platform: state
    entity_id: sensor.nicks_bedside_button_click
    to: single
    id: nick
  - platform: state
    entity_id: sensor.kates_bedside_button_click
    to: single
    id: kate
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: "nick"
        sequence:
          - service: light.toggle
            entity_id: light.nicks_bedside
      - conditions:
          - condition: trigger
            id: "kate"
        sequence:
          - service: light.toggle
            entity_id: light.kates_bedside
    default: []
mode: parallel
