id: '983479729828'
alias: 'kitchen button: toggle house blinds on button hold'
description: ''
trigger:
- platform: state
  entity_id: sensor.living_room_button_action
  to: hold
condition: []
action:
- service: cover.toggle
  entity_id: cover.all_blinds
mode: single
