- platform: template
  sensors:
    smart_plug_1_total_energy:
      friendly_name: Total Energy
      unit_of_measurement: kWh
      value_template: "{{ state_attr("switch.my_smart_plug", "total_energy_kwh") }}"
    smart_plug_1_energy_today:
      friendly_name: Energy Today
      unit_of_measurement: kWh
      value_template: "{{ state_attr("switch.my_smart_plug", "today_energy_kwh") }}"
    smart_plug_1_power:
      friendly_name: Power
      unit_of_measurement: W
      value_template: "{{ state_attr("switch.my_smart_plug", "current_power_w") }}"
    smart_plug_1_current:
      friendly_name: Current
      unit_of_measurement: A
      value_template: "{{ state_attr("switch.my_smart_plug", "current_a") }}"
    smart_plug_1_voltage:
      friendly_name: Voltage
      unit_of_measurement: V
      value_template: "{{ state_attr("switch.my_smart_plug", "voltage") }}"
