id: "1584944974594"
alias: "living_room: turn on the LED strip when the TV turns on or source changes"
description: ""
trigger:
  - entity_id: media_player.living_room_tv
    from: "off"
    platform: state
    to: "on"
condition:
  - condition: state
    entity_id: media_player.living_room_tv
    state: "on"
action:
  - service: select.select_option
    data:
      option: "* Color 1"
    target:
      entity_id: "select.tv_led_strip_color_palette"
  - data:
      rgb_color: [255, 170, 102]
      brightness: 128
      effect: Solid
    entity_id: light.tv_led_strip
    service: light.turn_on
