id: '1584944974594'
alias: 'living_room: when the TV turns on, turn on the LED strip'
description: ''
trigger:
  - entity_id: media_player.samsung_smart_tv
    from: 'off'
    platform: state
    to: 'on'
condition: []
action:
  - data:
      rgb_color:
        - 255
        - 181
        - 108
    entity_id: light.tv_led_strip
    service: light.turn_on
