alarm_control_panel:
  - platform: manual
    delay_time: 60
    arming_time: 60
    trigger_time: 120
    armed_night:
      delay_time: 15
    code: !secret alarm_code
    code_arm_required: false

automation:
  - id: "1601034054491"
    alias: "alarm: trigger when external door opened whilst armed"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.back_door_contact
          - binary_sensor.front_door_contact
        to: "on"
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: alarm_control_panel.ha_alarm
            state: armed_away
          - condition: state
            entity_id: alarm_control_panel.ha_alarm
            state: armed_night
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.ha_alarm
    mode: single

  - id: "1601034054492"
    alias: "alarm: trigger when motion detected whilst armed_away"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.living_room_motion_occupancy
          - binary_sensor.hallway_motion_occupancy
          - binary_sensor.study_motion_occupancy
          - binary_sensor.kitchen_motion_occupancy
          - binary_sensor.laundry_motion_occupancy
          - binary_sensor.spare_room_motion_occupancy
          - binary_sensor.bedroom_motion_occupancy
        to: "on"
    condition:
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: armed_away
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.ha_alarm
    mode: single

  - id: "1601034697138"
    alias: "alarm: send notification when triggered"
    description: ""
    trigger:
      - platform: state
        entity_id: alarm_control_panel.ha_alarm
        to: triggered
    condition:
      condition: not
      conditions:
        - condition: state
          entity_id: vacuum.osmo
          state: cleaning
        - condition: state
          entity_id: vacuum.osmo
          state: returning
    action:
      - service: notify.everyone
        data:
          title: Alarm Triggered
          message: The alarm was triggered at {{ now().strftime('%I:%M %p') }}
          data:
            group: alarm-status
            url: "/lovelace/security"
            entity_id: camera.front_door_high
            actions:
              - action: "DISARM_ALARM"
                title: "Disarm"
                authenticationRequired: true
                destructive: true
            push:
              sound:
                name: default
                critical: 1
                volume: 0
    mode: single

  - id: "1601035010807"
    alias: "alarm: send notification on disarm if triggered or pending"
    description: ""
    trigger:
      - platform: state
        entity_id: alarm_control_panel.ha_alarm
        to: disarmed
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: alarm_control_panel.ha_alarm
            state: pending
          - condition: state
            entity_id: alarm_control_panel.ha_alarm
            state: triggered
    action:
      - service: notify.everyone
        data:
          title: Alarm Disarmed
          message: The alarm was disarmed at {{ now().strftime('%I:%M %p') }}
          data:
            group: alarm-status
            tag: alarm-status
    mode: single

  - id: "1601035037271"
    alias: "alarm: send notification when pending"
    description: ""
    trigger:
      - platform: state
        entity_id: alarm_control_panel.ha_alarm
        to: pending
    condition: []
    action:
      - service: notify.everyone
        data:
          title: Alarm Pending
          message: The alarm was pending at {{ now().strftime('%I:%M %p') }}
          data:
            url: "/lovelace/security"
            entity_id: camera.front_door_high
            group: alarm-status
            tag: alarm-status
            actions:
              - action: "DISARM_ALARM"
                title: "Disarm"
                authenticationRequired: true
                destructive: true

    mode: single

  - id: "1601035065291"
    alias: "alarm: send notification when armed"
    description: ""
    trigger:
      - platform: state
        entity_id: alarm_control_panel.ha_alarm
        to:
          - armed_away
          - armed_night
    condition: []
    action:
      - service: notify.everyone
        data:
          title: Alarm Armed
          message: The alarm was {{ trigger.to_state.state }} at {{ now().strftime('%I:%M %p') }}
          data:
            group: alarm-status
            tag: alarm-status
            actions:
              - action: "DISARM_ALARM"
                title: "Disarm"
                authenticationRequired: true
                destructive: true
    mode: single

  - id: "1601035419737"
    alias: "alarm: disarm when everyone arrives home and armed/triggered/pending"
    description: ""
    trigger:
      - platform: state
        entity_id: group.all_people
        to: home
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: alarm_control_panel.ha_alarm
            state: armed_night
    action:
      - service: alarm_control_panel.alarm_disarm
        data:
          code: !secret alarm_code
        entity_id: alarm_control_panel.ha_alarm
    mode: single

  - id: "1601035712824"
    alias: "alarm: arm_away when everyone leaves home and disarmed"
    description: ""
    trigger:
      - platform: state
        entity_id: group.all_people
        to: not_home
    condition:
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: disarmed
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
    action:
      - service: alarm_control_panel.alarm_arm_away
        data: {}
        entity_id: alarm_control_panel.ha_alarm
    mode: single

  - id: "1601036735034"
    alias: "alarm: disarm when mobile app disarm action fired"
    description: ""
    trigger:
      - platform: event
        event_type: ios.notification_action_fired
        event_data:
          actionName: DISARM_ALARM
    condition: []
    action:
      - service: alarm_control_panel.alarm_disarm
        data:
          code: !secret alarm_code
        entity_id: alarm_control_panel.ha_alarm
    mode: single

  - id: "1601103558889"
    alias: "alarm: arm_night when no motion/activity detected"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.living_room_motion_occupancy
          - binary_sensor.hallway_motion_occupancy
          - binary_sensor.study_motion_occupancy
          - binary_sensor.laundry_motion_occupancy
          - binary_sensor.front_door_contact
          - binary_sensor.back_door_contact
        to:
          - "on"
          - "off"
    condition:
      - condition: time
        after: "22:30:00"
        before: "06:00:00"
      - condition: not
        conditions:
          - condition: state
            entity_id: media_player.living_room_tv
            state: "off"
    action:
      - delay: 00:15:00
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.living_room_motion_occupancy
            state: "off"
          - condition: state
            entity_id: binary_sensor.hallway_motion_occupancy
            state: "off"
          - condition: state
            entity_id: binary_sensor.study_motion_occupancy
            state: "off"
          - condition: state
            entity_id: binary_sensor.laundry_motion_occupancy
            state: "off"
      - condition: time
        after: "22:30:00"
        before: "06:00:00"
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: disarmed
      - service: alarm_control_panel.alarm_arm_night
        entity_id: alarm_control_panel.ha_alarm
    mode: restart

  - id: "1601101160650"
    alias: "alarm: disarm night at 7am or when internal motion detected"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.hallway_motion_occupancy
        to: "on"
      - platform: time
        at: 07:00:00
    condition:
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: armed_night
    action:
      - service: alarm_control_panel.alarm_disarm
        data:
          code: !secret alarm_code
        entity_id: alarm_control_panel.ha_alarm
    mode: single

  - id: "1601104910978"
    alias: "alarm: play sound on pending/triggered"
    description: ""
    trigger:
      - platform: state
        entity_id: alarm_control_panel.ha_alarm
        to: pending
      - platform: state
        entity_id: alarm_control_panel.ha_alarm
        to: triggered
    condition: []
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: alarm_control_panel.ha_alarm
                state: pending
            sequence:
              - service: script.set_siren
                data:
                  siren_entity: switch.study_siren_alarm
                  melody_entity: select.study_siren_melody
                  melody: "8"
                  volume_entity: select.study_siren_volume
                  volume: medium
                  duration_entity: number.study_siren_duration
                  duration: 1800
          - conditions:
              - condition: state
                entity_id: alarm_control_panel.ha_alarm
                state: triggered
            sequence:
              - service: script.set_siren
                data:
                  siren_entity: switch.study_siren_alarm
                  melody_entity: select.study_siren_melody
                  melody: "6"
                  volume_entity: select.study_siren_volume
                  volume: high
                  duration_entity: number.study_siren_duration
                  duration: 1800
        default: []
      - delay: 00:00:02
      - wait_template: >-
          {{ states('alarm_control_panel.ha_alarm') not in ('pending', 'triggered') }}
        continue_on_timeout: false
      - service: switch.turn_off
        target:
          entity_id: switch.study_siren_alarm
    mode: restart

  # Other Ideas:
  # Baesean sensor for in-bed?
