alarm_control_panel:
  - platform: manual
    delay_time: 60
    arming_time: 60
    trigger_time: 120

ios:
  push:
    categories:
      - name: Alarm
        identifier: alarm
        actions:
          - identifier: 'DISARM_ALARM'
            title: 'Disarm'
            activationMode: 'background'
            authenticationRequired: true
            destructive: true
            behavior: 'default'

automation:
  - id: '1601034054491'
    alias: 'alarm: trigger when external door opened whilst armed'
    description: ''
    trigger:
    - platform: state
      entity_id:
        - binary_sensor.balcony_door
        - binary_sensor.front_door
        - binary_sensor.laundry_door
      to: 'on'
    condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: armed_away
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: armed_night
    action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.ha_alarm
    mode: single

  - id: '1601034054492'
    alias: 'alarm: trigger when motion detected whilst armed_away'
    description: ''
    trigger:
    - platform: state
      entity_id:
        - binary_sensor.living_room_motion_occupancy
      to: 'on'
    condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
    action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.ha_alarm
    mode: single

  - id: '1601034697138'
    alias: 'alarm: send notification when triggered'
    description: ''
    trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: triggered
    condition: []
    action:
    - service: notify.everyone
      data:
        title: Alarm Triggered
        message: The alarm was triggered at {{ now().strftime('%I:%M %p') }}
        data:
          push:
            thread-id: alarm-status
            category: alarm
            sound:
              name: default
              critical: 1
    mode: single

  - id: '1601035010807'
    alias: 'alarm: send notification on disarm if triggered or pending'
    description: ''
    trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: disarmed
    condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: pending
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: triggered
    action:
    - service: notify.everyone
      data:
        title: Alarm Disarmed
        message: The alarm was disarmed at {{ now().strftime('%I:%M %p') }}
        data:
          apns_headers:
            apns-collapse-id: alarm-status
          push:
            thread-id: alarm-status
    mode: single

  - id: '1601035037271'
    alias: 'alarm: send notification when pending'
    description: ''
    trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: pending
    condition: []
    action:
    - service: notify.everyone
      data:
        title: Alarm Pending
        message: The alarm was pending at {{ now().strftime('%I:%M %p') }}
        data:
          apns_headers:
            apns-collapse-id: alarm-status
          push:
            thread-id: alarm-status
            category: alarm
    mode: single

  - id: '1601035065291'
    alias: 'alarm: send notification when armed'
    description: ''
    trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to:
        - armed_away
        - armed_night
    condition: []
    action:
    - service: notify.everyone
      data:
        title: Alarm Armed
        message: The alarm was {{ trigger.to_state.state }} at {{ now().strftime('%I:%M %p') }}
        data:
          apns_headers:
            apns-collapse-id: alarm-status
          push:
            category: alarm
            thread-id: alarm-status
    mode: single

  - id: '1601035419737'
    alias: 'alarm: disarm when everyone arrives home and armed/triggered/pending'
    description: ''
    trigger:
    - platform: state
      entity_id: group.all_people
      to: home
    condition:
    - condition: not
      conditions:
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: armed_night
    action:
    - service: alarm_control_panel.alarm_disarm
      data: {}
      entity_id: alarm_control_panel.ha_alarm
    mode: single

  - id: '1601035712824'
    alias: 'alarm: arm_away when everyone leaves home and disarmed'
    description: ''
    trigger:
    - platform: state
      entity_id: group.all_people
      to: not_home
    condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: disarmed
    action:
    - service: alarm_control_panel.alarm_arm_away
      data: {}
      entity_id: alarm_control_panel.ha_alarm
    mode: single

  - id: '1601036735034'
    alias: 'alarm: disarm when mobile app disarm action fired'
    description: ''
    trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: DISARM_ALARM
    condition: []
    action:
    - service: alarm_control_panel.alarm_disarm
      data: {}
      entity_id: alarm_control_panel.ha_alarm
    mode: single

  - id: '1601103558889'
    alias: 'alarm: arm_night when no motion/activity detected'
    description: ''
    trigger:
    - platform: state
      entity_id:
      - binary_sensor.living_room_motion_occupancy
      - binary_sensor.front_door
      - binary_sensor.balcony_door
      - binary_sensor.laundry_door
      - binary_sensor.bathroom_door
      to:
        - 'on'
        - 'off'
    condition:
    - condition: time
      after: '22:30:00'
      before: '06:00:00'
    action:
    - delay: 00:30:00
    - condition: state
      entity_id: binary_sensor.living_room_motion_occupancy
      state: 'off'
    - condition: time
      after: '22:30:00'
      before: '06:00:00'
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: disarmed
    - service: alarm_control_panel.alarm_arm_night
      entity_id: alarm_control_panel.ha_alarm
    mode: restart

  - id: '1601101160650'
    alias: 'alarm: disarm night at 7am or when internal motion detected'
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion_occupancy
      to: 'on'
    # Trigger on any (open/close) change to internal doors.
    - platform: state
      entity_id:
        - binary_sensor.bathroom_door
      to:
        - 'on'
        - 'off'
    - platform: time
      at: 07:00:00
    condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_night
    action:
    - service: alarm_control_panel.alarm_disarm
      data: {}
      entity_id: alarm_control_panel.ha_alarm
    mode: single

  - id: '1601104910978'
    alias: 'alarm: play sound on pending/triggered'
    description: ''
    trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: pending
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: triggered
    condition: []
    action:
    - choose:
      - conditions:
        - condition: state
          entity_id: alarm_control_panel.ha_alarm
          state: pending
        sequence:
        - service: media_player.volume_set
          data:
            volume_level: 0.2
          entity_id: media_player.study_speaker
        - service: media_player.play_media
          data:
            media_content_id: https://hass.mpl.nickwhyte.com/local/audio/alarm_pending_beep.mp3
            media_content_type: music
          entity_id: media_player.study_speaker
      - conditions:
        - condition: state
          entity_id: alarm_control_panel.ha_alarm
          state: triggered
        sequence:
        - service: media_player.volume_set
          data:
            volume_level: 0.1
          entity_id: media_player.study_speaker
        - service: media_player.play_media
          data:
            media_content_id: https://hass.mpl.nickwhyte.com/local/audio/alarm_triggered_siren.mp3
            media_content_type: music
          entity_id: media_player.study_speaker
      default: []
    - delay: 00:00:02
    - wait_template: >-
        {{ states('alarm_control_panel.ha_alarm') not in ('pending', 'triggered') }}
      continue_on_timeout: false
    - service: media_player.media_stop
      data: {}
      entity_id: media_player.study_speaker
    mode: restart

  # Other Ideas:
  # Baesean sensor for in-bed?
  # Air lock - notify on laundry door open without main door / recent at_home.
