binary_sensor:
  - platform: template
    sensors:
      some_soil_moisture_low:
        friendly_name: "Some Soil Moisture Low"
        value_template: >-
          {%- for s in states.sensor if 'soil_moisture' in s.entity_id and (is_state(s.entity_id, 'unavailable') or states(s.entity_id)|int < 20)  %}
            {%- if loop.first -%}
              True
            {%- endif %}
          {%- endfor %}
