homeassistant:
  customize:
    cover.living_room_blockout: &id001
      assumed_state: true
    cover.living_room_day: *id001
    cover.study_blockout: *id001
    cover.study_day: *id001
    cover.bedroom_door_day: *id001
    cover.bedroom_window_day: *id001
    cover.bedroom_door_blockout: *id001
    cover.bedroom_window_blockout: *id001
cover:
- platform: template
  covers:
    living_room_blockout:
      friendly_name: Living Room Blockout
      device_class: blind
      open_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 0
          action: OPEN
      close_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 0
          action: CLOSE
      stop_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 0
          action: STOP
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    living_room_day:
      friendly_name: Living Room Day
      device_class: blind
      open_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 20
          action: OPEN
      close_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 20
          action: CLOSE
      stop_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 20
          action: STOP
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    study_blockout:
      friendly_name: Study Blockout
      device_class: blind
      open_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 1
          action: OPEN
      close_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 1
          action: CLOSE
      stop_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 1
          action: STOP
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    study_day:
      friendly_name: Study Day
      device_class: blind
      open_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 21
          action: OPEN
      close_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 21
          action: CLOSE
      stop_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 21
          action: STOP
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    bedroom_door_day:
      friendly_name: Bedroom Door Day
      device_class: blind
      open_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 2
          action: OPEN
      close_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 2
          action: CLOSE
      stop_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 2
          action: STOP
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    bedroom_window_day:
      friendly_name: Bedroom Window Day
      device_class: blind
      open_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 22
          action: OPEN
      close_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 22
          action: CLOSE
      stop_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 22
          action: STOP
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    bedroom_door_blockout:
      friendly_name: Bedroom Door Blockout
      device_class: blind
      open_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 3
          action: OPEN
      close_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 3
          action: CLOSE
      stop_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 3
          action: STOP
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    bedroom_window_blockout:
      friendly_name: Bedroom Window Blockout
      device_class: blind
      open_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 4
          action: OPEN
      close_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 4
          action: CLOSE
      stop_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 4
          action: STOP
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
switch:
  platform: template
  switches:
    living_room_blockout_blind_pairing:
      friendly_name: Living Room Blockout Blind Pairing
      value_template: off
      turn_on:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 0
          action: PAIR
      turn_off: []
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    living_room_day_blind_pairing:
      friendly_name: Living Room Day Blind Pairing
      value_template: off
      turn_on:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 20
          action: PAIR
      turn_off: []
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    study_blockout_blind_pairing:
      friendly_name: Study Blockout Blind Pairing
      value_template: off
      turn_on:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 1
          action: PAIR
      turn_off: []
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    study_day_blind_pairing:
      friendly_name: Study Day Blind Pairing
      value_template: off
      turn_on:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 21
          action: PAIR
      turn_off: []
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    bedroom_door_day_blind_pairing:
      friendly_name: Bedroom Door Day Blind Pairing
      value_template: off
      turn_on:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 2
          action: PAIR
      turn_off: []
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    bedroom_window_day_blind_pairing:
      friendly_name: Bedroom Window Day Blind Pairing
      value_template: off
      turn_on:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 22
          action: PAIR
      turn_off: []
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    bedroom_door_blockout_blind_pairing:
      friendly_name: Bedroom Door Blockout Blind Pairing
      value_template: off
      turn_on:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 3
          action: PAIR
      turn_off: []
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    bedroom_window_blockout_blind_pairing:
      friendly_name: Bedroom Window Blockout Blind Pairing
      value_template: off
      turn_on:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 4
          action: PAIR
      turn_off: []
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
