homeassistant:
  customize:
    cover.bedroom_screen: &id001
      assumed_state: true
    cover.bedroom_blockout: *id001
    cover.study_screen: *id001
    cover.study_blockout: *id001
    cover.kitchen_screen: *id001
    cover.kitchen_blockout: *id001
    cover.living_right_screen: *id001
    cover.living_right_blockout: *id001
    cover.living_left_blockout: *id001
    cover.living_side_blockout: *id001
cover:
- platform: template
  covers:
    bedroom_screen:
      friendly_name: Bedroom Screen
      device_class: blind
      open_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 1
          action: OPEN
      close_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 1
          action: CLOSE
      stop_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 1
          action: STOP
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    bedroom_blockout:
      friendly_name: Bedroom Blockout
      device_class: blind
      open_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 2
          action: OPEN
      close_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 2
          action: CLOSE
      stop_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 2
          action: STOP
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    study_screen:
      friendly_name: Study Screen
      device_class: blind
      open_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 3
          action: OPEN
      close_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 3
          action: CLOSE
      stop_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 3
          action: STOP
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    study_blockout:
      friendly_name: Study Blockout
      device_class: blind
      open_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 4
          action: OPEN
      close_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 4
          action: CLOSE
      stop_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 4
          action: STOP
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    kitchen_screen:
      friendly_name: Kitchen Screen
      device_class: blind
      open_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 5
          action: OPEN
      close_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 5
          action: CLOSE
      stop_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 5
          action: STOP
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    kitchen_blockout:
      friendly_name: Kitchen Blockout
      device_class: blind
      open_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 6
          action: OPEN
      close_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 6
          action: CLOSE
      stop_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 6
          action: STOP
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    living_right_screen:
      friendly_name: Living Right Screen
      device_class: blind
      open_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 41
          channel_id: 1
          action: OPEN
      close_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 41
          channel_id: 1
          action: CLOSE
      stop_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 41
          channel_id: 1
          action: STOP
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    living_right_blockout:
      friendly_name: Living Right Blockout
      device_class: blind
      open_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 41
          channel_id: 2
          action: OPEN
      close_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 41
          channel_id: 2
          action: CLOSE
      stop_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 41
          channel_id: 2
          action: STOP
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    living_left_blockout:
      friendly_name: Living Left Blockout
      device_class: blind
      open_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 8
          action: OPEN
      close_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 8
          action: CLOSE
      stop_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 8
          action: STOP
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    living_side_blockout:
      friendly_name: Living Side Blockout
      device_class: blind
      open_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 9
          action: OPEN
      close_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 9
          action: CLOSE
      stop_cover:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 9
          action: STOP
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
switch:
  platform: template
  switches:
    bedroom_screen_blind_pairing:
      friendly_name: Bedroom Screen Blind Pairing
      value_template: off
      turn_on:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 1
          action: PAIR
      turn_off: []
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    bedroom_blockout_blind_pairing:
      friendly_name: Bedroom Blockout Blind Pairing
      value_template: off
      turn_on:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 2
          action: PAIR
      turn_off: []
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    study_screen_blind_pairing:
      friendly_name: Study Screen Blind Pairing
      value_template: off
      turn_on:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 3
          action: PAIR
      turn_off: []
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    study_blockout_blind_pairing:
      friendly_name: Study Blockout Blind Pairing
      value_template: off
      turn_on:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 4
          action: PAIR
      turn_off: []
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    kitchen_screen_blind_pairing:
      friendly_name: Kitchen Screen Blind Pairing
      value_template: off
      turn_on:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 5
          action: PAIR
      turn_off: []
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    kitchen_blockout_blind_pairing:
      friendly_name: Kitchen Blockout Blind Pairing
      value_template: off
      turn_on:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 6
          action: PAIR
      turn_off: []
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    living_right_screen_blind_pairing:
      friendly_name: Living Right Screen Blind Pairing
      value_template: off
      turn_on:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 41
          channel_id: 1
          action: PAIR
      turn_off: []
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    living_right_blockout_blind_pairing:
      friendly_name: Living Right Blockout Blind Pairing
      value_template: off
      turn_on:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 41
          channel_id: 2
          action: PAIR
      turn_off: []
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    living_left_blockout_blind_pairing:
      friendly_name: Living Left Blockout Blind Pairing
      value_template: off
      turn_on:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 8
          action: PAIR
      turn_off: []
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
    living_side_blockout_blind_pairing:
      friendly_name: Living Side Blockout Blind Pairing
      value_template: off
      turn_on:
        service: esphome.rf_controller_transmit
        data:
          remote_id: 40
          channel_id: 9
          action: PAIR
      turn_off: []
      availability_template: |-
        {{ is_state('binary_sensor.rf_controller_status', 'on') }}
