sensor:
  - platform: version
  - platform: template
    sensors:
      updater_newest_version:
        friendly_name: "Newest Version"
        value_template: "{{ state_attr('binary_sensor.updater', 'newest_version') }}"
