automation:
  - id: "1719053789067"
    alias: "gas: increment counter on impulse"
    description: ""
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.gas_impulse_contact
        from: "on"
        to: "off"
    condition: []
    action:
      - service: counter.increment
        metadata: {}
        data: {}
        target:
          entity_id: counter.gas_impulse
    mode: single

counter:
  gas_impulse:
    name: "Gas Impulse"
    icon: "mdi:meter-gas"
    step: 1

template:
  - sensor:
      - name: "Gas Usage (Volume)"
        unique_id: gas_usage_volume
        unit_of_measurement: m³
        device_class: gas
        state_class: total_increasing
        state: >
          {{ states('counter.gas_impulse')|float / 100 }}
      - name: "Gas Usage (Energy)"
        unique_id: gas_usage_energy
        unit_of_measurement: MJ
        device_class: energy
        state_class: total_increasing
        # m3 x Heating Value x Conversion factor
        state: >
          {{ states('sensor.gas_usage_volume')|float * 38.42 * 0.9650 }}

sensor:
  - platform: derivative
    name: "Gas Usage Rate 5m"
    source: sensor.gas_usage_energy
    unit_time: h
    time_window: "00:05:00"
    max_sub_interval: "00:00:15"
  - platform: derivative
    name: "Gas Usage Rate 10m"
    source: sensor.gas_usage_energy
    unit_time: h
    time_window: "00:10:00"
    max_sub_interval: "00:00:30"
  - platform: derivative
    name: "Gas Usage Rate 30m"
    source: sensor.gas_usage_energy
    unit_time: h
    time_window: "00:30:00"
    max_sub_interval: "00:01:00"
  - platform: derivative
    name: "Gas Usage Rate 1h"
    source: sensor.gas_usage_energy
    unit_time: h
    time_window: "01:00:00"
    max_sub_interval: "00:01:00"
