frontend:
  themes: !include_dir_merge_named ../themes

automation:
  - id: "frontend_set_default_theme"
    alias: "at startup, set the default theme"
    trigger:
      platform: homeassistant
      event: start
    action:
      service: frontend.set_theme
      data:
        name: "Google Theme"
