recorder:
  purge_keep_days: 14
  exclude:
      entities: sensor.samsung_m283x_series_uptime
  
automation:
  - id: '1585649979000'
    alias: every Sunday at 3am, purge and repack the database
    description: ''
    trigger:
      - at: 00:03:00
        platform: time
    condition:
      - condition: time
        weekday:
          - sun
    action:
      - data:
          keep_days: 14
          repack: true
        service: recorder.purge
