spotify:
  client_id: !secret spotify_client_id_nick
  client_secret: !secret spotify_client_secret_nick

spotcast:
  sp_dc: !secret spotcast_sp_dc
  sp_key: !secret spotcast_sp_key

sensor:
  - platform: spotcast

switch:
  - platform: template
    switches:
      play_music:
        friendly_name: "Play Music"
        icon_template: "mdi:speaker"
        value_template: >
          {{
           is_state('media_player.spotify_nicholas_whyte', 'playing') and
           is_state_attr('media_player.spotify_nicholas_whyte', 'source', 'Soundbar Cast')
          }}
        turn_on:
          - service: spotcast.start
            data:
              entity_id: media_player.soundbar_cast
              force_playback: true
        turn_off:
          - service: media_player.media_pause
            target:
              entity_id: media_player.soundbar_cast
