spotcast:
  sp_dc: !secret spotcast_nick_sp_dc
  sp_key: !secret spotcast_nick_sp_key
  accounts:
    nick:
      sp_dc: !secret spotcast_nick_sp_dc
      sp_key: !secret spotcast_nick_sp_key
    kate:
      sp_dc: !secret spotcast_kate_sp_dc
      sp_key: !secret spotcast_kate_sp_key

sensor:
  - platform: spotcast

switch:
  - platform: template
    switches:
      play_music:
        friendly_name: "Play Music"
        icon_template: "mdi:speaker"
        value_template: >
          {{ is_state('media_player.owntone_server', 'playing') }}
        turn_on:
          - service: media_player.play_media
            data:
              media_content_id: http://www.abc.net.au/res/streaming/audio/mp3/triplej.pls
              media_content_type: playlist
            target:
              entity_id: media_player.owntone_server
          - service: media_player.turn_on
            target:
              entity_id:
                - media_player.owntone_output_soundbar
                - media_player.owntone_output_bathroom
                - media_player.owntone_output_study
                - media_player.owntone_output_bedroom
        turn_off:
          - service: media_player.turn_off
            target:
              entity_id: media_player.owntone_server
