sensor:
  - platform: ha_transportnsw
    api_key: !secret transport_nsw_api_key
    origin_id: 222310
    destination_id: 200060
    trip_wait_time: 0
    transport_type: 1 # Only trains
    return_info: medium
    strict_transport_type: true
    trips_to_create: 3
    include_realtime_location: true
    include_alerts: normal
    alert_types:
      - lineInfo
      - routeInfo
    name: "Mortdale to Central"
