sensor:
  - platform: statistics
    name: "Outdoor Temperature Max 8h"
    entity_id: sensor.ecowitt_hub_outdoor_temperature
    state_characteristic: value_max
    max_age:
      hours: 8
  - platform: statistics
    name: "Outdoor Temperature Mean 1d"
    entity_id: sensor.ecowitt_hub_outdoor_temperature
    state_characteristic: mean
    max_age:
      hours: 24
  - platform: statistics
    name: "Outdoor Temperature Max 1d"
    entity_id: sensor.ecowitt_hub_outdoor_temperature
    state_characteristic: value_max
    max_age:
      hours: 24
  - platform: statistics
    name: "Outdoor Temperature Mean 2d"
    entity_id: sensor.ecowitt_hub_outdoor_temperature
    state_characteristic: mean
    max_age:
      hours: 48
  - platform: statistics
    name: "Outdoor Temperature Max 2d"
    entity_id: sensor.ecowitt_hub_outdoor_temperature
    state_characteristic: value_max
    max_age:
      hours: 48
  - platform: statistics
    name: "Outdoor Temperature Mean 3d"
    entity_id: sensor.ecowitt_hub_outdoor_temperature
    state_characteristic: mean
    max_age:
      hours: 72
  - platform: statistics
    name: "Outdoor Temperature Max 3d"
    entity_id: sensor.ecowitt_hub_outdoor_temperature
    state_characteristic: value_max
    max_age:
      hours: 72

utility_meter:
  rain_weekly:
    name: "Rain Weekly"
    unique_id: rain_weekly
    source: sensor.ecowitt_hub_total_rain
    cycle: weekly
  rain_daily:
    name: "Rain Daily"
    unique_id: rain_daily
    source: sensor.ecowitt_hub_total_rain
    cycle: daily
  rain_hourly:
    name: "Rain Hourly"
    unique_id: rain_hourly
    source: sensor.ecowitt_hub_total_rain
    cycle: hourly
