id: '1603065400361'
alias: 'bedroom: toggle bedsides on wall switch 2 change'
description: ''
trigger:
- platform: state
  entity_id: binary_sensor.bedroom_channel_2_input
  to: 'on'
  from: 'off'
- platform: state
  entity_id: binary_sensor.bedroom_channel_2_input
  to: 'off'
  from: 'on'
condition: []
action:
  - service: light.toggle
    entity_id: light.bedroom_lamps
mode: queued
max: 10
