id: "983479729222"
alias: "Bedroom Wall button: toggle bedroom door blind on button hold"
description: ""
trigger:
  - platform: state
    entity_id: sensor.bedroom_wall_button_action
    to: hold
condition: []
action:
  - service: cover.toggle
    entity_id: cover.bedroom_door
mode: single
