id: '1600953878712'
alias: 'bedroom: toggle bedsides on button press'
description: ''
trigger:
- platform: state
  entity_id: sensor.bedroom_button_click
  to: single
condition: []
action:
- service: light.toggle
  data: {}
  entity_id: light.bedroom_lamps
mode: single
