id: "1603018075175"
alias: "bedroom: turn on the bedroom lamps before bed"
description: ""
trigger:
  - platform: time
    at: "22:15:00"
condition:
  - condition: state
    entity_id: group.all_people
    state: home
  # Only turn on if occupants are not already in bed.
  - condition: state
    entity_id: binary_sensor.in_bed
    state: "off"
  # Only turn on if the TV is on or some lights are on
  # TODO(NW): Remove in favour of making above in_bed sensor better.
  - condition: or
    conditions:
      - condition: state
        entity_id: media_player.living_room_tv
        state: "on"
      - condition: state
        entity_id: binary_sensor.some_lights_on
        state: "on"
action:
  - service: light.turn_on
    data: {}
    entity_id: light.bedroom_lamps
mode: single
