- id: '1527999374641'
  alias: Family & Kitch up 6.15am
  trigger:
  - at: 06:15:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: cover.blindkit_front_3_door_right
    service: cover.open_cover
  - data:
      entity_id: cover.blindkit_front_2_door_left
    service: cover.open_cover
  - data:
      entity_id: cover.blindkit_front_1_left
    service: cover.open_cover
  - data:
      entity_id: cover.blindkit_back_right
    service: cover.open_cover
  - data:
      entity_id: cover.blindkit_back_left
    service: cover.open_cover

- id: '1528004893114'
  alias: Family & Kitch Part Down 5:30pm
  trigger:
  - at: '17:30:00'
    platform: time
  condition: []
  action:
  - alias: ''
    data:
      entity_id: cover.blindkit_front_4_right
    service: cover.close_cover
  - data:
      entity_id: cover.blindkit_front_2_door_left
    service: cover.close_cover
  - data:
      entity_id: cover.blindkit_front_1_left
    service: cover.close_cover
  - data:
      entity_id: cover.blindkit_back_left
    service: cover.close_cover

- id: '1528005097586'
  alias: Family & Kitch Down all 10pm
  trigger:
  - at: '22:00:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: cover.blindkit_front_4_right
    service: cover.close_cover
  - data:
      entity_id: cover.blindkit_front_3_door_right
    service: cover.close_cover
  - data:
      entity_id: cover.blindkit_front_2_door_left
    service: cover.close_cover
  - data:
      entity_id: cover.blindkit_front_1_left
    service: cover.close_cover
  - data:
      entity_id: cover.blindkit_back_right
    service: cover.close_cover
  - data:
      entity_id: cover.blindkit_back_left
    service: cover.close_cover

- id: '1528005630746'
  alias: Up-Hall Blockout Open 7.30am
  trigger:
  - at: 07:30:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: cover.blindkit_upstairs_hall_blockout
    service: cover.open_cover

- id: '1528005697426'
  alias: Up-Hall Blockout Down 5.30pm
  trigger:
  - at: '17:30:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: cover.blindkit_upstairs_hall_blockout
    service: cover.close_cover

- alias: Open Nicks Blinds at 8am weekdays
  id: '1521974624434'
  trigger:
  - at: 08:00:00
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: cover.open_cover
    data:
      entity_id: cover.blindkit_nicks_front
  - service: cover.open_cover
    data:
      entity_id: cover.blindkit_nicks_side
