- platform: mqtt
  name: blindkit_nick_front
  command_topic: /things/blindkit/18fe3499d274/send_code
  availability_topic: /things/blindkit/18fe3499d274/status
  qos: 1
  payload_open: 100,0,OPEN
  payload_close: 100,0,CLOSE
  payload_stop: 100,0,STOP
- platform: mqtt
  name: blindkit_nick_side
  command_topic: /things/blindkit/18fe3499d274/send_code
  availability_topic: /things/blindkit/18fe3499d274/status
  qos: 1
  payload_open: 100,1,OPEN
  payload_close: 100,1,CLOSE
  payload_stop: 100,1,STOP
- platform: mqtt
  name: blindkit_upstairs_hall
  command_topic: /things/blindkit/18fe3499d274/send_code
  availability_topic: /things/blindkit/18fe3499d274/status
  qos: 1
  payload_open: 100,2,OPEN
  payload_close: 100,2,CLOSE
  payload_stop: 100,2,STOP
- platform: mqtt
  name: blindkit_charlotte_side
  command_topic: /things/blindkit/18fe3499d274/send_code
  availability_topic: /things/blindkit/18fe3499d274/status
  qos: 1
  payload_open: 100,3,OPEN
  payload_close: 100,3,CLOSE
  payload_stop: 100,3,STOP
- platform: mqtt
  name: blindkit_oly_side
  command_topic: /things/blindkit/18fe3499d274/send_code
  availability_topic: /things/blindkit/18fe3499d274/status
  qos: 1
  payload_open: 100,4,OPEN
  payload_close: 100,4,CLOSE
  payload_stop: 100,4,STOP
- platform: mqtt
  name: blindkit_oly_back
  command_topic: /things/blindkit/18fe3499d274/send_code
  availability_topic: /things/blindkit/18fe3499d274/status
  qos: 1
  payload_open: 100,5,OPEN
  payload_close: 100,5,CLOSE
  payload_stop: 100,5,STOP
- platform: mqtt
  name: blindkit_joe_back
  command_topic: /things/blindkit/18fe3499d274/send_code
  availability_topic: /things/blindkit/18fe3499d274/status
  qos: 1
  payload_open: 100,6,OPEN
  payload_close: 100,6,CLOSE
  payload_stop: 100,6,STOP
- platform: mqtt
  name: blindkit_master_front_left
  command_topic: /things/blindkit/18fe3499d274/send_code
  availability_topic: /things/blindkit/18fe3499d274/status
  qos: 1
  payload_open: 100,7,OPEN
  payload_close: 100,7,CLOSE
  payload_stop: 100,7,STOP
- platform: mqtt
  name: blindkit_master_front_right
  command_topic: /things/blindkit/18fe3499d274/send_code
  availability_topic: /things/blindkit/18fe3499d274/status
  qos: 1
  payload_open: 100,8,OPEN
  payload_close: 100,8,CLOSE
  payload_stop: 100,8,STOP
- platform: mqtt
  name: blindkit_back_left
  command_topic: /things/blindkit/18fe3499d258/send_code
  availability_topic: /things/blindkit/18fe3499d258/status
  qos: 1
  payload_open: 101,0,OPEN
  payload_close: 101,0,CLOSE
  payload_stop: 101,0,STOP
- platform: mqtt
  name: blindkit_back_right
  command_topic: /things/blindkit/18fe3499d258/send_code
  availability_topic: /things/blindkit/18fe3499d258/status
  qos: 1
  payload_open: 101,1,OPEN
  payload_close: 101,1,CLOSE
  payload_stop: 101,1,STOP
- platform: mqtt
  name: blindkit_front_1_left
  command_topic: /things/blindkit/18fe3499d258/send_code
  availability_topic: /things/blindkit/18fe3499d258/status
  qos: 1
  payload_open: 101,2,OPEN
  payload_close: 101,2,CLOSE
  payload_stop: 101,2,STOP
- platform: mqtt
  name: blindkit_front_2_door_left
  command_topic: /things/blindkit/18fe3499d258/send_code
  availability_topic: /things/blindkit/18fe3499d258/status
  qos: 1
  payload_open: 101,3,OPEN
  payload_close: 101,3,CLOSE
  payload_stop: 101,3,STOP
- platform: mqtt
  name: blindkit_front_3_door_right
  command_topic: /things/blindkit/18fe3499d258/send_code
  availability_topic: /things/blindkit/18fe3499d258/status
  qos: 1
  payload_open: 101,4,OPEN
  payload_close: 101,4,CLOSE
  payload_stop: 101,4,STOP
- platform: mqtt
  name: blindkit_front_4_right
  command_topic: /things/blindkit/18fe3499d258/send_code
  availability_topic: /things/blindkit/18fe3499d258/status
  qos: 1
  payload_open: 101,5,OPEN
  payload_close: 101,5,CLOSE
  payload_stop: 101,5,STOP
