# Adapted from: https://community.home-assistant.io/t/monitor-your-hdd-smart-status/194132
---

sensor:
  - platform: command_line
    name: smartctl_sda_json
    command: "/bin/cat /config/smartctl/sda.json"
    value_template: "{{ value_json.smartctl.exit_status }}"
    json_attributes:
      - smartctl
      - device
      - model_name
      - user_capacity
      - smart_status
      - ata_smart_attributes
      - temperature
      - power_on_time
      - power_cycle_count
      - ata_smart_self_test_log
    scan_interval: 60
  - platform: command_line
    name: smartctl_sdb_json
    command: "/bin/cat /config/smartctl/sdb.json"
    value_template: "{{ value_json.smartctl.exit_status }}"
    json_attributes:
      - smartctl
      - device
      - model_name
      - user_capacity
      - smart_status
      - ata_smart_attributes
      - temperature
      - power_on_time
      - power_cycle_count
      - ata_smart_self_test_log
    scan_interval: 60
  - platform: command_line
    name: smartctl_sdc_json
    command: "/bin/cat /config/smartctl/sdc.json"
    value_template: "{{ value_json.smartctl.exit_status }}"
    json_attributes:
      - smartctl
      - device
      - model_name
      - user_capacity
      - smart_status
      - ata_smart_attributes
      - temperature
      - power_on_time
      - power_cycle_count
      - ata_smart_self_test_log
    scan_interval: 60
  - platform: template
    sensors:
      smartctl_sda:
        friendly_name: '/dev/sda smartctl exit status'
        icon_template: mdi:harddisk
        value_template: "{{ states('sensor.smartctl_sda_json') }}"
        attribute_templates:
          device_name: "{{ state_attr('sensor.smartctl_sda_json', 'device').name }}"
          model_name: "{{ state_attr('sensor.smartctl_sda_json', 'model_name') }}"
      smartctl_sda_smart_status:
        friendly_name: '/dev/sda SMART Status'
        icon_template: mdi:information
        value_template: "{{ 'passed' if state_attr('sensor.smartctl_sda_json', 'smart_status').passed else 'Failed' }}"
      smartctl_sda_temperature:
        friendly_name: '/dev/sda Temperature'
        icon_template: mdi:thermometer
        value_template: "{{ state_attr('sensor.smartctl_sda_json', 'temperature').current }}"
        unit_of_measurement: '°C'
      smartctl_sda_power_on_time:
        friendly_name: '/dev/sda Power On Time'
        icon_template: mdi:clock
        value_template: "{{ state_attr('sensor.smartctl_sda_json', 'power_on_time').hours }}"
        unit_of_measurement: 'Days'
      smartctl_sda_power_cycle_count:
        friendly_name: '/dev/sda Power Cycle Count'
        icon_template: mdi:counter
        value_template: "{{ state_attr('sensor.smartctl_sda_json', 'power_cycle_count') }}"
        unit_of_measurement: 'Cycles'
      smartctl_sda_last_test_type:
        friendly_name: '/dev/sda Last Test Type'
        icon_template: mdi:harddisk-plus
        value_template: "{{ state_attr('sensor.smartctl_sda_json', 'ata_smart_self_test_log').standard.table[0].type.string }}"
      smartctl_sda_last_test_status:
        friendly_name: '/dev/sda Last Test Status'
        icon_template: mdi:harddisk-plus
        value_template: "{{ state_attr('sensor.smartctl_sda_json', 'ata_smart_self_test_log').standard.table[0].status.string }}"

      smartctl_sdb:
        friendly_name: '/dev/sdb smartctl exit status'
        icon_template: mdi:harddisk
        value_template: "{{ states('sensor.smartctl_sdb_json') }}"
        attribute_templates:
          device_name: "{{ state_attr('sensor.smartctl_sdb_json', 'device').name }}"
          model_name: "{{ state_attr('sensor.smartctl_sdb_json', 'model_name') }}"
      smartctl_sdb_smart_status:
        friendly_name: '/dev/sdb SMART Status'
        icon_template: mdi:information
        value_template: "{{ 'passed' if state_attr('sensor.smartctl_sdb_json', 'smart_status').passed else 'Failed' }}"
      smartctl_sdb_temperature:
        friendly_name: '/dev/sdb Temperature'
        icon_template: mdi:thermometer
        value_template: "{{ state_attr('sensor.smartctl_sdb_json', 'temperature').current }}"
        unit_of_measurement: '°C'
      smartctl_sdb_power_on_time:
        friendly_name: '/dev/sdb Power On Time'
        icon_template: mdi:clock
        value_template: "{{ state_attr('sensor.smartctl_sdb_json', 'power_on_time').hours }}"
        unit_of_measurement: 'Days'
      smartctl_sdb_power_cycle_count:
        friendly_name: '/dev/sdb Power Cycle Count'
        icon_template: mdi:counter
        value_template: "{{ state_attr('sensor.smartctl_sdb_json', 'power_cycle_count') }}"
        unit_of_measurement: 'Cycles'
      smartctl_sdb_last_test_type:
        friendly_name: '/dev/sdb Last Test Type'
        icon_template: mdi:harddisk-plus
        value_template: "{{ state_attr('sensor.smartctl_sdb_json', 'ata_smart_self_test_log').standard.table[0].type.string }}"
      smartctl_sdb_last_test_status:
        friendly_name: '/dev/sdb Last Test Status'
        icon_template: mdi:harddisk-plus
        value_template: "{{ state_attr('sensor.smartctl_sdb_json', 'ata_smart_self_test_log').standard.table[0].status.string }}"

      smartctl_sdc:
        friendly_name: '/dev/sdb smartctl exit status'
        icon_template: mdi:harddisk
        value_template: "{{ states('sensor.smartctl_sdc_json') }}"
        attribute_templates:
          device_name: "{{ state_attr('sensor.smartctl_sdc_json', 'device').name }}"
          model_name: "{{ state_attr('sensor.smartctl_sdc_json', 'model_name') }}"
      smartctl_sdc_smart_status:
        friendly_name: '/dev/sdc SMART Status'
        icon_template: mdi:information
        value_template: "{{ 'passed' if state_attr('sensor.smartctl_sdc_json', 'smart_status').passed else 'Failed' }}"
      smartctl_sdc_temperature:
        friendly_name: '/dev/sdc Temperature'
        icon_template: mdi:thermometer
        value_template: "{{ state_attr('sensor.smartctl_sdc_json', 'temperature').current }}"
        unit_of_measurement: '°C'
      smartctl_sdc_power_on_time:
        friendly_name: '/dev/sdc Power On Time'
        icon_template: mdi:clock
        value_template: "{{ state_attr('sensor.smartctl_sdc_json', 'power_on_time').hours }}"
        unit_of_measurement: 'Days'
      smartctl_sdc_power_cycle_count:
        friendly_name: '/dev/sdc Power Cycle Count'
        icon_template: mdi:counter
        value_template: "{{ state_attr('sensor.smartctl_sdc_json', 'power_cycle_count') }}"
        unit_of_measurement: 'Cycles'
      smartctl_sdc_last_test_type:
        friendly_name: '/dev/sdc Last Test Type'
        icon_template: mdi:harddisk-plus
        value_template: "{{ state_attr('sensor.smartctl_sdc_json', 'ata_smart_self_test_log').standard.table[0].type.string }}"
      smartctl_sdc_last_test_status:
        friendly_name: '/dev/sdc Last Test Status'
        icon_template: mdi:harddisk-plus
        value_template: "{{ state_attr('sensor.smartctl_sdc_json', 'ata_smart_self_test_log').standard.table[0].status.string }}"

binary_sensor:
  - platform: template
    sensors:
      smartctl_sda_last_test_passed:
        friendly_name: '/dev/sda Last Test Passed'
        icon_template: mdi:harddisk-plus
        value_template: >-
          {%- if 'passed' in state_attr('sensor.smartctl_sda_json', 'ata_smart_self_test_log').standard.table[0].status -%}
            {{ state_attr('sensor.smartctl_sda_json', 'ata_smart_self_test_log').standard.table[0].status.passed }}
          {%- else -%}
            True
          {%- endif -%}
      smartctl_sdb_last_test_passed:
        friendly_name: '/dev/sdb Last Test Passed'
        icon_template: mdi:harddisk-plus
        value_template: >-
          {%- if 'passed' in state_attr('sensor.smartctl_sdb_json', 'ata_smart_self_test_log').standard.table[0].status -%}
            {{ state_attr('sensor.smartctl_sdb_json', 'ata_smart_self_test_log').standard.table[0].status.passed }}
          {%- else -%}
            True
          {%- endif -%}
      smartctl_sdc_last_test_passed:
        friendly_name: '/dev/sdc Last Test Passed'
        icon_template: mdi:harddisk-plus
        value_template: >-
          {%- if 'passed' in state_attr('sensor.smartctl_sdc_json', 'ata_smart_self_test_log').standard.table[0].status -%}
            {{ state_attr('sensor.smartctl_sdc_json', 'ata_smart_self_test_log').standard.table[0].status.passed }}
          {%- else -%}
            True
          {%- endif -%}

automation:
  - id: '1595157734038'
    alias: when hard disk SMART test fails, notify Nick
    description: ''
    trigger:
    - entity_id: binary_sensor.smartctl_sda_last_test_passed
      platform: state
      to: 'off'
    - entity_id: binary_sensor.smartctl_sdb_last_test_passed
      platform: state
      to: 'off'
    - entity_id: binary_sensor.smartctl_sdc_last_test_passed
      platform: state
      to: 'off'
    condition: []
    action:
    - data:
        message: A hard disk is failing in store.313a.nickwhyte.com
      service: notify.telegram_nick
