sensor:
  - platform: uptime
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: disk_use
        arg: /
      - type: disk_free
        arg: /
      - type: memory_use_percent
      - type: memory_use
      - type: memory_free
      - type: swap_use_percent
      - type: swap_use
      - type: swap_free
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: processor_use
      - type: network_in
        arg: enp2s0
      - type: network_out
        arg: enp2s0
      - type: ipv4_address
        arg: enp2s0
      - type: ipv6_address
        arg: enp2s0
      - type: last_boot
