id: "029438302948"
alias: "blinds: open blinds screens on mornings"
description: ""
trigger:
  - platform: time
    at: 09:15:00
condition:
  - condition: state
    entity_id: group.all_people
    state: home
  - condition: state
    entity_id: input_boolean.away_mode
    state: "off"
action:
  # Handle the case where no motion has been detected, perhaps it's a public
  # holiday and wanted a sleep in. If no motion since dawn, then delay until
  # motion has been detected.
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.internal_motion_occupancy_since_dawn
            below: "1"
        sequence:
          - wait_for_trigger:
              - platform: numeric_state
                entity_id: sensor.internal_motion_occupancy_since_dawn
                above: "0"
            timeout: "02:00:00" # Wait for up to two hours (11:15am), then continue
            continue_on_timeout: true
  - service: cover.open_cover
    data: {}
    entity_id:
      - cover.living_right_screen
      - cover.kitchen_screen
mode: single
