id: "160095323447334"
alias: "laundry: return vacuum on laundry door button click when cleaning"
description: ""
trigger:
  - platform: state
    entity_id: sensor.laundry_button_click
    to: single
condition:
  - condition: state
    entity_id: vacuum.osmo
    state: cleaning
action:
  - service: script.osmo_cancel_cleaning
    data: {}
mode: single
