id: "1600953234419038"
alias: "laundry: summon vacuum on button hold"
description: ""
trigger:
  - platform: state
    entity_id: sensor.laundry_button_action
    to: hold
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: vacuum.osmo
        state: cleaning
action:
  - service: script.osmo_summon
    data: {}
mode: single
