id: "160095323482734"
alias: "laundry: vacuum auto on laundry button single click"
description: ""
trigger:
  - platform: state
    entity_id: sensor.laundry_button_click
    to: single
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: vacuum.osmo
        state: cleaning
action:
  - service: script.osmo_auto_clean
    data: {}
mode: single
