id: '1626173678031'
alias: 'living room ambiance: toggle for sunrise/sunset'
description: ''
trigger:
- platform: sun
  event: sunrise
  id: sunrise
- platform: sun
  event: sunset
  id: sunset
condition:
- condition: state
  entity_id: group.all_people
  state: home
action:
- choose:
  - conditions:
    - condition: trigger
      id: sunrise
    sequence:
    - service: light.turn_off
      target:
        entity_id: light.living_room_ambiance
  - conditions:
    - condition: trigger
      id: sunset
    sequence:
    - condition: and
      conditions:
      - condition: state
        entity_id: light.living_room_downlights
        state: 'off'
    - service: light.turn_on
      target:
        entity_id: light.living_room_ambiance
      data: {}
  default: []
mode: single
