id: "1626176121966"
alias: "living room ambiance: turn on when presence is detected"
description: ""
trigger:
  - platform: state
    entity_id: group.all_people
    from: not_home
    to: home
condition:
  - condition: or
    conditions:
      - condition: sun
        before: sunrise
      - condition: sun
        after: sunset
  - condition: state
    entity_id: input_boolean.away_mode
    state: "off"
  - condition: state
    entity_id: light.living_room_downlights
    state: "off"
action:
  - service: script.turn_on
    target:
      entity_id: script.wled_set_scene
    data:
      variables:
        entity_id_base: cabinet_glow
        effect: Solid
        color_palette: "* Color 1"
  - service: script.turn_on
    target:
      entity_id: script.wled_set_scene
    data:
      variables:
        entity_id_base: breakfast_bar
        effect: Twinkleup
        color_palette: "* Color 1"
mode: single
