alias: "hass updater: clear persistent notification on update available"
id: "hass_updater_clear_persistent_notification_on_update_available"
trigger:
  - platform: state
    entity_id: binary_sensor.updater
    to: "off"
action:
  - service: persistent_notification.dismiss
    data:
      notification_id: "update_available"
