id: "1733996368210"
alias: "inverter: reload modbus on stale state"
description: ""
triggers:
  - trigger: template
    value_template:
      "{{ as_timestamp(now()) - as_timestamp(states.sensor.inverter_meter_power_raw.last_changed)
      > 600 }}"
conditions: []
actions:
  - action: modbus.reload
    metadata: {}
    data: {}
  - action: persistent_notification.create
    metadata: {}
    data:
      title: Modbus Reloaded
      message: Inverter meter power last changed > 600 seconds.
mode: single
