id: '160095323482724'
alias: 'living_room: vacuum all areas on front door button hold'
description: ''
trigger:
- platform: state
  entity_id: sensor.front_door_button_action
  to: hold
condition:
- condition: not
  conditions:
    - condition: state
      entity_id: vacuum.osmo
      state: cleaning
action:
- service: script.osmo_clean_all_areas
  data: {}
mode: single
