id: '160095323482734'
alias: 'living_room: vacuum tiled areas on front door button single click'
description: ''
trigger:
- platform: state
  entity_id: sensor.front_door_button_click
  to: single
condition:
- condition: not
  conditions:
    - condition: state
      entity_id: vacuum.osmo
      state: cleaning
action:
- service: script.osmo_clean_tiled_areas
  data: {}
mode: single
