id: "160095322198347127"
alias: "dog_door: toggle locked out on living room button press"
description: ""
trigger:
  - platform: state
    entity_id: sensor.living_room_button_action
    to: hold
action:
  - alias: "lock/unlock"
    choose:
      - conditions:
          - condition: state
            entity_id: lock.backyard_locked_out
            state: "locked"
        sequence:
          - service: lock.unlock
            target:
              entity_id: lock.backyard_locked_out
      - conditions:
          - condition: state
            entity_id: lock.backyard_locked_out
            state: "unlocked"
        sequence:
          - service: lock.lock
            target:
              entity_id: lock.backyard_locked_out
mode: single
