id: "1584944187934"
alias: "living_room: turn on lamp on presence detected"
description: ""
trigger:
  - entity_id: group.all_people
    from: not_home
    platform: state
    to: home
condition:
  - after: sunset
    after_offset: -00:60:00
    condition: sun
action:
  - service: light.turn_on
    data: {}
    entity_id: light.living_room_lamp
  - if:
      - condition: state
        entity_id: light.stitch_lamp
        state: "off"
    then:
      - service: light.turn_on
        data:
          brightness_pct: 30
        entity_id:
          - light.stitch_lamp
