id: '1584944760804'
alias: 'living_room: when the sun sets and someone is home, turn on the living room lamp'
description: ''
trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
condition:
  - condition: state
    entity_id: group.all_people
    state: home
action:
  - device_id: 8c28feb17fb74368ac8b2a30f2a66355
    domain: switch
    entity_id: switch.living_room_lamp
    type: turn_on
