id: "1605957739472"
alias: "living_room: turn on lamp on living motion detected at night"
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.living_room_motion_occupancy
    from: "off"
    to: "on"
    id: "living_room"
condition:
  - condition: or
    conditions:
      - condition: time
        after: "23:00:00"
      - condition: sun
        before: sunrise
  - condition: state
    entity_id: light.living_room_lamp
    state: "off"
  - condition: state
    entity_id: input_boolean.guest_mode
    state: "off"
  # Don't perform action if trigger is living_room && robot running
  - condition: template
    value_template: >
      {{ trigger.id != 'living_room' or states('vacuum.crystal') not in ['cleaning', 'returning'] }}
action:
  - service: light.turn_on
    entity_id: light.living_room_lamp
  - wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.internal_motion_occupancy
        from: "on"
        to: "off"
        for: 00:01:00
  - service: light.turn_off
    data: {}
    entity_id: light.living_room_lamp
mode: single
