id: "348573498568"
alias: "kitchen ambiance: toggle for kitchen brightness"
description: >
  A temporary (approximation) automation to toggle the kitchen LED strip brightness
  based on room brightness as measured by kitchen motion sensor. Not the best, slow 
  response time since lux is only sent when new motion is detected, so this will lag
  behind room ambient light levels but will do until kitchen downlights are automated
trigger:
  - platform: numeric_state
    entity_id: sensor.kitchen_motion_illuminance_lux
    above: 60
    id: lights_on
  - platform: numeric_state
    entity_id: sensor.kitchen_motion_illuminance_lux
    below: 30
    id: lights_off
condition:
  - condition: or
    conditions:
      - condition: sun
        before: sunrise
      - condition: sun
        after: sunset
      - condition: numeric_state
        entity_id: sensor.fo79_weather_lux
        below: 100
  - condition: state
    entity_id: group.all_people
    state: "home"
action:
  - choose:
      - conditions:
          - condition: trigger
            id: lights_off
        sequence:
          - service: "light.turn_on"
            data:
              brightness_pct: 10
            target:
              entity_id:
                - light.kitchen_strip
                - light.bench_strip
    default:
      # We must pre-set brightness with a separate call, then turn the light
      # on due to SetOption20
      - service: light.turn_on
        data:
          brightness_pct: 80
        target:
          entity_id:
            - light.kitchen_strip
            - light.bench_strip
      - service: light.turn_on
        target:
          entity_id:
            - light.kitchen_strip
            - light.bench_strip
mode: single
