id: "1626173674033"
alias: "kitchen ambiance: toggle for sunrise/sunset"
description: ""
trigger:
  - platform: sun
    event: sunrise
    id: sunrise
  - platform: sun
    event: sunset
    id: sunset
condition:
  - condition: state
    entity_id: group.all_people
    state: home
action:
  - choose:
      - conditions:
          - condition: trigger
            id: sunrise
        sequence:
          - service: light.turn_off
            target:
              entity_id:
                - light.kitchen_strip
                - light.bench_strip
      - conditions:
          - condition: trigger
            id: sunset
        sequence:
          - condition: not
            conditions:
              - condition: state
                entity_id: light.kitchen
                state: "on"
          - service: light.turn_on
            data:
              brightness_pct: 60
            target:
              entity_id:
                - light.kitchen_strip
                - light.bench_strip
    default: []
mode: single
