id: "98437594832563"
alias: "kitchen ambiance: toggle for downlights state"
description: ""
trigger:
  - platform: state
    entity_id: light.kitchen
    to:
      - "on"
      - "off"
condition:
  - condition: or
    conditions:
      - condition: sun
        before: sunrise
      - condition: sun
        after: sunset
  - condition: state
    entity_id: input_boolean.away_mode
    state: "off"
  - condition: state
    entity_id: group.all_people
    state: "home"
action:
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.to_state.state == "on" }}
        sequence:
          - service: "light.turn_off"
            target:
              entity_id:
                - light.kitchen_strip
                - light.bench_strip
    default:
      - service: light.turn_on
        data:
          brightness_pct: 60
        target:
          entity_id:
            - light.kitchen_strip
            - light.bench_strip
mode: single
