id: "16261761231966"
alias: "kitchen ambiance: turn on when presence is detected"
description: ""
trigger:
  - platform: state
    entity_id: group.all_people
    from: not_home
    to: home
condition:
  - after: sunset
    after_offset: -00:60:00
    condition: sun
  - condition: state
    entity_id: input_boolean.away_mode
    state: "off"
  - condition: not
    conditions:
      - condition: state
        entity_id: light.kitchen
        state: "on"
action:
  # We must pre-set brightness with a separate call, then turn the light
  # on due to SetOption20
  - service: light.turn_on
    data:
      brightness_pct: 10
    target:
      entity_id:
        - light.kitchen_strip
        - light.bench_strip
  - service: light.turn_on
    target:
      entity_id:
        - light.kitchen_strip
        - light.bench_strip
mode: single
