id: "1626174525614"
alias: "kitchen ambiance: turn on when motion detected at night"
description: ""
trigger:
  - platform: state
    entity_id: binary_sensor.hallway_motion_occupancy
    from: "off"
    to: "on"
  - platform: state
    entity_id: binary_sensor.kitchen_motion_occupancy
    from: "off"
    to: "on"
condition:
  - condition: or
    conditions:
      - condition: time
        after: "23:00"
      - condition: sun
        before: sunrise
  - condition: state
    entity_id: light.kitchen_strip
    state: "off"
  - condition: state
    entity_id: light.bench_strip
    state: "off"
  - condition: not
    conditions:
      - condition: state
        entity_id: light.kitchen
        state: "on"
  - condition: state
    entity_id: input_boolean.guest_mode
    state: "off"
  - condition: state
    entity_id: group.all_people
    state: home
action:
  # We must pre-set brightness with a separate call, then turn the light
  # on due to SetOption20
  - service: light.turn_on
    data:
      brightness_pct: 30
    target:
      entity_id:
        - light.kitchen_strip
        - light.bench_strip
  - service: light.turn_on
    data:
      transition: 5
    target:
      entity_id:
        - light.kitchen_strip
        - light.bench_strip
  - wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.internal_motion_occupancy
        from: "on"
        to: "off"
        for: 00:01:00
      # Bail out if the downlights turn on
      - platform: state
        entity_id: light.kitchen
        from: "off"
        to: "on"
      - platform: state
        entity_id: light.lounge
        from: "off"
        to: "on"
      # Bail out if the ambient light is turned off
      - platform: state
        entity_id: light.kitchen_strip
        from: "on"
        to: "off"
      - platform: state
        entity_id: light.bench_strip
        from: "on"
        to: "off"
    timeout: 00:10:00
    continue_on_timeout: true
  - service: light.turn_off
    target:
      entity_id:
        - light.kitchen_strip
        - light.bench_strip
mode: single
