esphome:
  name: doorbell
  platform: ESP32
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "doorbell"
    password: !secret wifi_fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin: GPIO34
    name: "Doorbell"
    filters:
      - delayed_on: 100ms
  - platform: status
    name: "RF Controller Status"

sensor:
  - platform: uptime
    name: Doorbell Uptime
  - platform: wifi_signal
    name: "Doorbell Wifi Signal"
    update_interval: 60s

switch:
  - platform: gpio
    pin: GPIO32
    id: relay
  - platform: template
    name: "Door Key"
    icon: "mdi:key"
    lambda: |-
      if (id(relay).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
    - switch.turn_on: relay
    - delay: 3000ms
    - switch.turn_off: relay
    turn_off_action:
    - switch.turn_off: relay
