esphome:
  name: hallway-ir
  friendly_name: Hallway IR

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret hallway_ir_api_enryption_key

ota:
  - platform: esphome
    password: !secret hallway_ir_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Hallway-Ir Fallback Hotspot"
    password: !secret wifi_fallback_password

captive_portal:

remote_transmitter:
  pin: GPIO5
  carrier_duty_percent: 50%

climate:
  - platform: fujitsu_general
    sensor: ac_return_climate_temperature
    name: "Hallway"

sensor:
  - platform: homeassistant
    id: "ac_return_climate_temperature"
    name: "ac_return_climate_temperature"
    entity_id: sensor.ac_return_climate_temperature

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
  connection_slots: 3