esphome:
  name: irrigation

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Irrigation Fallback Hotspot"
    password: !secret wifi_fallback_password

captive_portal:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: Sprinkle IP Address
    ssid:
      name: Sprinkle Connected SSID
    bssid:
      name: Sprinkle Connected BSSID
    mac_address:
      name: Sprinkle Mac Wifi Address


binary_sensor:
  - platform: status
    name: Sprinkle Status

sensor:
  - platform: uptime
    name: Irrigation Uptime
  - platform: wifi_signal
    name: Irrigation WiFi Signal
    update_interval: 60s
  - platform: template
    name: "Front Herbs Time Remaining"
    id: time_remaining_front_herbs
    unit_of_measurement: seconds
  - platform: template
    name: "Front Lawn Time Remaining"
    id: time_remaining_front_lawn
    unit_of_measurement: seconds
  - platform: template
    name: "Front Drippers Time Remaining"
    id: time_remaining_front_drippers
    unit_of_measurement: seconds
  - platform: template
    name: "Back Herbs Time Remaining"
    id: time_remaining_back_herbs
    unit_of_measurement: seconds
  - platform: template
    name: "Back Lawn Time Remaining"
    id: time_remaining_back_lawn
    unit_of_measurement: seconds
  - platform: template
    name: "Back Drippers Time Remaining"
    id: time_remaining_back_drippers
    unit_of_measurement: seconds

switch:
  - platform: gpio
    pin:
      number: GPIO12
    id: front_herbs_power
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin:
      number: GPIO21
    id: front_lawn_power
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin:
      number: GPIO19
    id: front_drippers_power
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin:
      number: GPIO32
    id: back_herbs_power
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin:
      number: GPIO33
    id: back_lawn_power
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin:
      number: GPIO13
    id: back_drippers_power
    restore_mode: ALWAYS_OFF
  
  - platform: template
    name: "Front Herbs"
    icon: "mdi:water"
    lambda: "return id(front_herbs_power).state;"
    turn_on_action:
    - switch.turn_on: front_herbs_power
    - script.execute: countdown_front_herbs
    - delay: !lambda "return id(front_herbs_watering_duration).state * 60 * 1000;"
    - switch.turn_off: front_herbs_power
    turn_off_action:
    - switch.turn_off: front_herbs_power
    on_turn_off:
    - script.stop: countdown_front_herbs
    - sensor.template.publish:
        id: time_remaining_front_herbs
        state: 0
  - platform: template
    name: "Front Lawn"
    icon: "mdi:water"
    lambda: "return id(front_lawn_power).state;"
    turn_on_action:
    - switch.turn_on: front_lawn_power
    - script.execute: countdown_front_lawn
    - delay: !lambda "return id(front_lawn_watering_duration).state * 60 * 1000;"
    - switch.turn_off: front_lawn_power
    turn_off_action:
    - switch.turn_off: front_lawn_power
    on_turn_off:
    - script.stop: countdown_front_lawn
    - sensor.template.publish:
        id: time_remaining_front_lawn
        state: 0
  - platform: template
    name: "Front Drippers"
    icon: "mdi:water"
    lambda: "return id(front_drippers_power).state;"
    turn_on_action:
    - switch.turn_on: front_drippers_power
    - script.execute: countdown_front_drippers
    - delay: !lambda "return id(front_drippers_watering_duration).state * 60 * 1000;"
    - switch.turn_off: front_drippers_power
    turn_off_action:
    - switch.turn_off: front_drippers_power
    on_turn_off:
    - script.stop: countdown_front_drippers
    - sensor.template.publish:
        id: time_remaining_front_drippers
        state: 0

  - platform: template
    name: "Back Herbs"
    icon: "mdi:water"
    lambda: "return id(back_herbs_power).state;"
    turn_on_action:
    - switch.turn_on: back_herbs_power
    - script.execute: countdown_back_herbs
    - delay: !lambda "return id(back_herbs_watering_duration).state * 60 * 1000;"
    - switch.turn_off: back_herbs_power
    turn_off_action:
    - switch.turn_off: back_herbs_power
    on_turn_off:
    - script.stop: countdown_back_herbs
    - sensor.template.publish:
        id: time_remaining_back_herbs
        state: 0
  - platform: template
    name: "Back Lawn"
    icon: "mdi:water"
    lambda: "return id(back_lawn_power).state;"
    turn_on_action:
    - switch.turn_on: back_lawn_power
    - script.execute: countdown_back_lawn
    - delay: !lambda "return id(back_lawn_watering_duration).state * 60 * 1000;"
    - switch.turn_off: back_lawn_power
    turn_off_action:
    - switch.turn_off: back_lawn_power
    on_turn_off:
    - script.stop: countdown_back_lawn
    - sensor.template.publish:
        id: time_remaining_back_lawn
        state: 0
  - platform: template
    name: "Back Drippers"
    icon: "mdi:water"
    lambda: "return id(back_drippers_power).state;"
    turn_on_action:
    - switch.turn_on: back_drippers_power
    - script.execute: countdown_back_drippers
    - delay: !lambda "return id(back_drippers_watering_duration).state * 60 * 1000;"
    - switch.turn_off: back_drippers_power
    turn_off_action:
    - switch.turn_off: back_drippers_power
    on_turn_off:
    - script.stop: countdown_back_drippers
    - sensor.template.publish:
        id: time_remaining_back_drippers
        state: 0

number:
  - platform: template
    name: "Front Herbs Watering Duration"
    id: 'front_herbs_watering_duration'
    optimistic: true
    min_value: 5
    max_value: 30
    restore_value: true
    initial_value: 10
    step: 1
  - platform: template
    name: "Front Lawn Watering Duration"
    id: 'front_lawn_watering_duration'
    optimistic: true
    min_value: 10
    max_value: 45
    restore_value: true
    initial_value: 15
    step: 1
  - platform: template
    name: "Front Drippers Watering Duration"
    id: 'front_drippers_watering_duration'
    optimistic: true
    min_value: 10
    max_value: 60
    restore_value: true
    initial_value: 30
    step: 1
  - platform: template
    name: "Back Herbs Watering Duration"
    id: 'back_herbs_watering_duration'
    optimistic: true
    min_value: 5
    max_value: 30
    restore_value: true
    initial_value: 10
    step: 1
  - platform: template
    name: "Back Lawn Watering Duration"
    id: 'back_lawn_watering_duration'
    optimistic: true
    min_value: 10
    max_value: 45
    restore_value: true
    initial_value: 15
    step: 1
  - platform: template
    name: "Back Drippers Watering Duration"
    id: 'back_drippers_watering_duration'
    optimistic: true
    min_value: 10
    max_value: 60
    restore_value: true
    initial_value: 30
    step: 1

globals:
  - id: front_herbs_time_remaining
    type: int
    restore_value: no
    initial_value: '0'
  - id: front_lawn_time_remaining
    type: int
    restore_value: no
    initial_value: '0'
  - id: front_drippers_time_remaining
    type: int
    restore_value: no
    initial_value: '0'
  - id: back_herbs_time_remaining
    type: int
    restore_value: no
    initial_value: '0'
  - id: back_lawn_time_remaining
    type: int
    restore_value: no
    initial_value: '0'
  - id: back_drippers_time_remaining
    type: int
    restore_value: no
    initial_value: '0'


script:

  - id: countdown_front_herbs
    then:
      - lambda: 'id(front_herbs_time_remaining) = id(front_herbs_watering_duration).state * 60;'
      - while:
          condition:
            lambda: "return id(front_herbs_time_remaining) > 0;"
          then:
            - sensor.template.publish:
                id: time_remaining_front_herbs
                state: !lambda 'return id(front_herbs_time_remaining);'
            - delay: 5 seconds
            - lambda: "id(front_herbs_time_remaining) -= 5;"
  - id: countdown_front_lawn
    then:
      - lambda: 'id(front_lawn_time_remaining) = id(front_lawn_watering_duration).state * 60;'
      - while:
          condition:
            lambda: "return id(front_lawn_time_remaining) > 0;"
          then:
            - sensor.template.publish:
                id: time_remaining_front_lawn
                state: !lambda 'return id(front_lawn_time_remaining);'
            - delay: 5 seconds
            - lambda: "id(front_lawn_time_remaining) -= 5;"
  - id: countdown_front_drippers
    then:
      - lambda: 'id(front_drippers_time_remaining) = id(front_drippers_watering_duration).state * 60;'
      - while:
          condition:
            lambda: "return id(front_drippers_time_remaining) > 0;"
          then:
            - sensor.template.publish:
                id: time_remaining_front_drippers
                state: !lambda 'return id(front_drippers_time_remaining);'
            - delay: 5 seconds
            - lambda: "id(front_drippers_time_remaining) -= 5;"
  - id: countdown_back_herbs
    then:
      - lambda: 'id(back_herbs_time_remaining) = id(back_herbs_watering_duration).state * 60;'
      - while:
          condition:
            lambda: "return id(back_herbs_time_remaining) > 0;"
          then:
            - sensor.template.publish:
                id: time_remaining_back_herbs
                state: !lambda 'return id(back_herbs_time_remaining);'
            - delay: 5 seconds
            - lambda: "id(back_herbs_time_remaining) -= 5;"
  - id: countdown_back_lawn
    then:
      - lambda: 'id(back_lawn_time_remaining) = id(back_lawn_watering_duration).state * 60;'
      - while:
          condition:
            lambda: "return id(back_lawn_time_remaining) > 0;"
          then:
            - sensor.template.publish:
                id: time_remaining_back_lawn
                state: !lambda 'return id(back_lawn_time_remaining);'
            - delay: 5 seconds
            - lambda: "id(back_lawn_time_remaining) -= 5;"
  - id: countdown_back_drippers
    then:
      - lambda: 'id(back_drippers_time_remaining) = id(back_drippers_watering_duration).state * 60;'
      - while:
          condition:
            lambda: "return id(back_drippers_time_remaining) > 0;"
          then:
            - sensor.template.publish:
                id: time_remaining_back_drippers
                state: !lambda 'return id(back_drippers_time_remaining);'
            - delay: 5 seconds
            - lambda: "id(back_drippers_time_remaining) -= 5;"