esphome:
  name: irrigation
  friendly_name: "Irrigation"
  area: "Yard"  # Default area for the controller

  areas:
    - id: front_yard
      name: "Front Yard"
    - id: back_yard
      name: "Back Yard"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
api:
ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Irrigation Fallback Hotspot"
    password: !secret wifi_fallback_password

captive_portal:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: Sprinkle IP Address
    ssid:
      name: Sprinkle Connected SSID
    bssid:
      name: Sprinkle Connected BSSID
    mac_address:
      name: Sprinkle Mac Wifi Address

binary_sensor:
  - platform: status
    name: Sprinkle Status

sensor:
  - platform: uptime
    name: Irrigation Uptime
  - platform: wifi_signal
    name: Irrigation WiFi Signal
    update_interval: 60s

# Irrigation zones are defined as packages to reduce duplication
packages:
  front_herbs: !include
    file: packages/irrigation-zone.yaml
    vars:
      name: "Front Herbs"
      device_id: front_herbs
      area_id: front_yard
      relay_pin: GPIO12
      min_duration: 1
      max_duration: 30
      initial_duration: 10
  front_lawn: !include
    file: packages/irrigation-zone.yaml
    vars:
      name: "Front Lawn"
      device_id: front_lawn
      area_id: front_yard
      relay_pin: GPIO21
      min_duration: 10
      max_duration: 45
      initial_duration: 15
  front_drippers: !include
    file: packages/irrigation-zone.yaml
    vars:
      name: "Front Drippers"
      device_id: front_drippers
      area_id: front_yard
      relay_pin: GPIO19
      min_duration: 10
      max_duration: 60
      initial_duration: 30
  back_herbs: !include
    file: packages/irrigation-zone.yaml
    vars:
      name: "Back Herbs"
      device_id: back_herbs
      area_id: back_yard
      relay_pin: GPIO32
      min_duration: 1
      max_duration: 30
      initial_duration: 10
  back_lawn: !include
    file: packages/irrigation-zone.yaml
    vars:
      name: "Back Lawn"
      device_id: back_lawn
      area_id: back_yard
      relay_pin: GPIO13
      min_duration: 10
      max_duration: 45
      initial_duration: 15
  back_drippers: !include
    file: packages/irrigation-zone.yaml
    vars:
      name: "Back Drippers"
      device_id: back_drippers
      area_id: back_yard
      relay_pin: GPIO33
      min_duration: 10
      max_duration: 60
      initial_duration: 30

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
  connection_slots: 3

