esphome:
  name: living-aq
  friendly_name: Living AQ

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret living_aq_api_encryption_key

ota:
  - platform: esphome
    password: !secret living_aq_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Living-Aq Fallback Hotspot"
    password: !secret wifi_fallback_password

captive_portal:
    
i2c:
  sda: GPIO8
  scl: GPIO9
  scan: true
  id: bus_a

sensor:
  - platform: scd4x
    address: 0x62
    co2:
      name: "CO2"
    temperature:
      name: "Temperature"
      id: scd41_temperature
    humidity:
      name: "Humidity"
      id: scd41_humidity

  # SGP30 (TVOC & 'equivalent' eCO2) with humidity compensation
  - platform: sgp30
    address: 0x58
    # update_interval: 1s           # SGP30 wants frequent reads
    tvoc:
      name: "TVOC"
    eco2:
      name: "eCO2"
    compensation:
      # Use SCD41 for better compensation:
      # ESPHome will compute absolute humidity from temp+RH
      temperature_source: scd41_temperature
      humidity_source: scd41_humidity

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""

  - platform: uptime
    type: seconds
    name: Uptime Sensor

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
  connection_slots: 3