esphome:
  name: rf_controller
  platform: ESP8266
  board: esp01_1m
  includes:
    - raex_blind_tx.h

wifi:
  ssid: !secret smart_wifi_ssid
  password: !secret smart_wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "rf_controller"
    password: !secret wifi_fallback_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

custom_component:
  - lambda: |-
      auto raex_blind_transmit = new RaexBlindTransmitComponent();
      return {raex_blind_transmit};

binary_sensor:
  - platform: status
    name: "RF Controller Status"