esphome:
  name: study-hub
  platform: ESP32
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret smart_wifi_ssid
  password: !secret smart_wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "study-hub"
    password: !secret wifi_fallback_password

captive_portal:

i2c:
  sda: 18
  scl: 19
  scan: true
  id: bus_a

esp32_ble_tracker:
bluetooth_proxy:

sensor:
  - platform: sgp30
    eco2:
      name: "Study eCO2"
      accuracy_decimals: 1
      filters:
      - sliding_window_moving_average:
          window_size: 60
          send_every: 60
    tvoc:
      name: "Study TVOC"
      accuracy_decimals: 1
      filters:
      - sliding_window_moving_average:
          window_size: 60
          send_every: 60
    store_baseline: no
    address: 0x58
    update_interval: 1s

  - platform: xiaomi_miscale
    mac_address: 'C8:47:8C:CA:49:0C'
    weight:
      name: "Xiaomi Mi Scale Weight"
      id: weight_miscale
      on_value:
        then:
          - lambda: |-
              if (id(weight_miscale).state >= 58) {
                return id(weight_nick).publish_state(x);
              } else if (id(weight_miscale).state >= 45) {
                return id(weight_kate).publish_state(x);
              }
  - platform: template
    name: Weight Nick
    id: weight_nick
    unit_of_measurement: 'kg'
    icon: mdi:weight-kilogram
    accuracy_decimals: 2
  - platform: template
    name: Weight Kate
    id: weight_kate
    unit_of_measurement: 'kg'
    icon: mdi:weight-kilogram
    accuracy_decimals: 2
