id: '1606546810796'
alias: 'doorbell: unlock the door on webhook call'
description: ''
trigger:
- platform: webhook
  webhook_id: !secret doorbell_webhook_id
condition: []
action:
- service: lock.unlock
  data: {}
  entity_id: lock.complex_door
mode: single
