
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.2"

[[constraint]]
  name = "github.com/brutella/hc"
  branch = "nwhyte/update-mdns"
  source = "github.com/nickw444/hc"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "2.2.5"

# Fix MDNS issues https://github.com/grandcat/zeroconf/issues/28
[[override]]
  name = "github.com/grandcat/zeroconf"
  revision = "8ad40c89978a7b2102ff98743831bf5cdb454f9f"
