id: "1626341264291"
alias: "dining cabinet: set colour temperature at sunrise/sunset"
description: ""
trigger:
  - platform: sun
    event: sunset
    id: sunset
  - platform: sun
    event: sunrise
    id: sunrise
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: sunset
        sequence:
          - service: script.wled_set_color
            data:
              topic: wled/cabinet-glow
              color: "#FF975E"
    default:
      - service: script.wled_set_color
        data:
          topic: wled/cabinet-glow
          color: "#FFB690"
mode: single
