id: "98437594832798"
alias: "dining cabinet: toggle for living room downlights state"
description: ""
trigger:
  - platform: state
    entity_id: light.living_room_downlights
    to:
      - "on"
      - "off"
condition:
  - condition: or
    conditions:
      - condition: sun
        before: sunrise
      - condition: sun
        after: sunset
  - condition: state
    entity_id: input_boolean.away_mode
    state: "off"
  - condition: state
    entity_id: group.all_people
    state: "home"
action:
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.to_state.state == "on" }}
        sequence:
          - service: "light.turn_off"
            target:
              entity_id: light.cabinet_glow_calibrated
    default:
      - service: script.wled_set_scene
        data:
          entity_id_base: cabinet_glow
          brightness: 255
          effect: Solid
          color_palette: "* Color 1"
mode: single
