id: '1626173678030'
alias: 'dining cabinet: toggle for sunrise/sunset'
description: ''
trigger:
- platform: sun
  event: sunrise
  id: sunrise
- platform: sun
  event: sunset
  id: sunset
  offset: '-30'
condition:
- condition: state
  entity_id: group.all_people
  state: home
action:
- choose:
  - conditions:
    - condition: trigger
      id: sunrise
    sequence:
    - service: light.turn_off
      target:
        entity_id: light.cabinet_glow
  - conditions:
    - condition: trigger
      id: sunset
    sequence:
    - condition: and
      conditions:
      - condition: state
        entity_id: group.all_people
        state: home
    - service: light.turn_on
      target:
        entity_id: light.cabinet_glow
      data: {}
  default: []
mode: single
