id: '1626174325612'
alias: 'dining cabinet: turn on when motion detected at night'
description: ''
trigger:
- platform: state
  entity_id: binary_sensor.living_room_motion_occupancy
  from: 'off'
  to: 'on'
condition:
- condition: or
  conditions:
  - condition: time
    after: '23:00'
  - condition: sun
    before: sunrise
- condition: state
  entity_id: light.cabinet_glow
  state: 'off'
- condition: state
  entity_id: input_boolean.guest_mode
  state: 'off'
action:
- service: light.turn_on
  target:
    entity_id: light.cabinet_glow
  data:
    brightness_pct: 80
    transition: 5
- wait_for_trigger:
  - platform: state
    entity_id: binary_sensor.internal_motion_occupancy
    from: 'on'
    to: 'off'
    for: 00:01:00
  timeout: 00:10:00
- service: light.turn_off
  target:
    entity_id: light.cabinet_glow
mode: single
