id: '1613560357086'
alias: 'presence: cancel dog cam noise notification snooze timer on presence detected'
description: ''
trigger:
- platform: state
  entity_id: group.all_people
  from: not_home
  to: home
condition: []
action:
- service: timer.cancel
  data: {}
  entity_id: timer.camera_noise_notification_snooze_timer
mode: single
