id: '1584944287383'
alias: 'presence: turn off house lights when everyone leaves'
description: ''
trigger:
  - entity_id: group.all_people
    for: 00:05:00
    platform: state
    to: not_home
condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
action:
  - data: {}
    entity_id: all
    service: light.turn_off
