binary_sensor:
  - platform: bayesian
    name: "Bathroom Shower Occupancy"
    prior: 0.02
    observations:
      - entity_id: "binary_sensor.bathroom_climate_humidity_elevated"
        prob_given_true: 0.95
        prob_given_false: 0.1
        platform: "state"
        to_state: "on"
      - entity_id: "binary_sensor.bathroom_motion_detected_recently"
        prob_given_true: 0.9
        # Assuming 1 hour spent daily in bathroom not showering
        prob_given_false: 0.05
        platform: "state"
        to_state: "on"
