binary_sensor:
  - platform: bayesian
    prior: 0.1
    observations:
      # Living Room TV
      # Bedroom Lights OFF
      # Living Lights OFF
      # Bathroom Lights OFF
      # Bedroom Lights ON -> OFF
      # After 11pm
      

      - entity_id: "switch.kitchen_lights"
        prob_given_true: 0.6
        prob_given_false: 0.2
        platform: "state"
        to_state: "on"
